# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name='icon')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_it', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('color', models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('abstract', models.TextField(blank=True, verbose_name='abstract')),
                ('abstract_it', models.TextField(blank=True, null=True, verbose_name='abstract')),
                ('abstract_en', models.TextField(blank=True, null=True, verbose_name='abstract')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('cover', models.ImageField(blank=True, upload_to='landing/', verbose_name='cover')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'presentation',
                'verbose_name_plural': 'presentations',
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing.Presentation'),
        ),
    ]
