# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30)),
                ('event_date', models.DateField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='landing.Presentation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='profile',
        ),
        migrations.AlterField(
            model_name='feature',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='landing.Presentation'),
        ),
        migrations.DeleteModel(
            name='Timeline',
        ),
    ]
