# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170924_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='staff_special_color',
            field=models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='presentation',
            name='staff_special_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
