# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170923_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='color',
            field=models.CharField(choices=[('Blue', 'info'), ('Rose', 'primary'), ('Red', 'danger'), ('Green', 'success')], default='info', max_length=30),
            preserve_default=False,
        ),
    ]
