# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20180104_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_it',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
