# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20170925_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='paper_url',
            field=models.URLField(blank=True),
        ),
    ]
