# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 14:19
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180104_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'feature', 'verbose_name_plural': 'features'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='color',
            field=models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='cover',
            field=models.ImageField(blank=True, upload_to='landing/', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
