# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20170923_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='landing/'),
        ),
    ]
