# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_presentation_features_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label')),
                ('label_it', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
                ('label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Feature Cover',
                'verbose_name_plural': 'Feature Covers',
            },
        ),
        migrations.AlterField(
            model_name='presentation',
            name='features_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.FeaturesCover'),
        ),
        migrations.DeleteModel(
            name='FeatureCover',
        ),
    ]
