# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20180105_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_en',
            field=models.TextField(blank=True, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract_it',
            field=models.TextField(blank=True, null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
