# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20180217_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurescover',
            options={'verbose_name': 'Features Cover', 'verbose_name_plural': 'Features Covers'},
        ),
        migrations.AlterField(
            model_name='presentation',
            name='features_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.FeaturesCover', verbose_name='features cover'),
        ),
    ]
