# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180220_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationcover',
            name='default',
        ),
        migrations.AddField(
            model_name='presentationcover',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='presentationcover',
            name='section',
            field=models.CharField(choices=[('DES', 'description'), ('FEA', 'features')], default='DES', max_length=3, verbose_name='section'),
        ),
    ]
