# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20180220_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationcover',
            name='active',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='presentation_covers',
        ),
        migrations.AddField(
            model_name='presentation',
            name='presentation_covers',
            field=models.ManyToManyField(blank=True, null=True, to='landing.PresentationCover', verbose_name='presentation covers'),
        ),
    ]
