# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_auto_20180220_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_covers',
            field=models.ManyToManyField(blank=True, to='landing.PresentationCover', verbose_name='presentation covers'),
        ),
    ]
