# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20180224_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_covers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.PresentationCover', verbose_name='presentation covers'),
        ),
    ]
