# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_auto_20180224_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='presentation_covers',
        ),
        migrations.AddField(
            model_name='presentationcover',
            name='presentation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='landing.Presentation', verbose_name='presentation'),
            preserve_default=False,
        ),
    ]
