# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_auto_20180224_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentationcover',
            name='presentation',
        ),
        migrations.DeleteModel(
            name='PresentationCover',
        ),
    ]
