# Generated by Django 2.0.8 on 2018-09-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_aboutcover'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcover',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='aboutcover',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
    ]
