# Generated by Django 2.0.8 on 2018-10-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0025_auto_20180903_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
