# Generated by Django 2.0.8 on 2018-10-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0026_auto_20181018_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='image',
            field=models.URLField(default='', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
