# Generated by Django 2.0.8 on 2018-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0027_auto_20181018_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
    ]
