# Generated by Django 2.0.8 on 2019-01-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0028_auto_20181018_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile',
        ),
        migrations.DeleteModel(
            name='AboutCover',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
