# Generated by Django 2.0.8 on 2019-01-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_auto_20190119_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='projects_description',
            field=models.TextField(blank=True, verbose_name='projects description'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='projects_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='projects description'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='projects_description_it',
            field=models.TextField(blank=True, null=True, verbose_name='projects description'),
        ),
    ]
