# Generated by Django 2.0.8 on 2019-03-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0030_auto_20190120_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='cover',
        ),
    ]
