# Generated by Django 2.0.8 on 2019-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0032_presentation_primary_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='primary_link',
            field=models.CharField(blank=True, max_length=50, verbose_name='primary link'),
        ),
    ]
