# Generated by Django 2.0.8 on 2019-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0033_auto_20190324_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='primary_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='primary link'),
        ),
    ]
