# Generated by Django 2.0.8 on 2019-03-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0034_auto_20190324_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='primary_link',
        ),
        migrations.AddField(
            model_name='presentation',
            name='featured_link',
            field=models.CharField(default='', max_length=150, verbose_name='featured link'),
            preserve_default=False,
        ),
    ]
