# Generated by Django 2.0.8 on 2019-03-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0035_auto_20190324_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='featured_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='featured label'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='featured_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='featured label'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='featured_label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='featured label'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='featured_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='featured link'),
        ),
    ]
