# Generated by Django 2.0.8 on 2019-03-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0036_auto_20190324_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='template',
            field=models.CharField(choices=[('left_header.html', 'left standard header'), ('centered_header.html', 'centered standard header')], default='centered_header.html', max_length=50),
            preserve_default=False,
        ),
    ]
