# Generated by Django 2.1.7 on 2019-04-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0039_auto_20190402_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='featured_link_en',
        ),
        migrations.RemoveField(
            model_name='presentation',
            name='featured_link_it',
        ),
    ]
