# Generated by Django 2.1.7 on 2019-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0042_auto_20190409_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.URLField(default='', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
