# Generated by Django 2.1.7 on 2019-04-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0043_auto_20190411_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='order index'),
            preserve_default=False,
        ),
    ]
