# Generated by Django 2.1.7 on 2019-04-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0044_section_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
