# Generated by Django 2.1.7 on 2019-04-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('landing', '0045_section_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.AddField(
            model_name='section',
            name='publishablemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel'),
            preserve_default=False,
        ),
    ]
