# Generated by Django 2.1.7 on 2019-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0049_section_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='featured_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='featured label'),
        ),
        migrations.AddField(
            model_name='section',
            name='featured_link',
            field=models.CharField(blank=True, max_length=150, verbose_name='featured link'),
        ),
        migrations.AddField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('', '')], default='', max_length=50, verbose_name='template'),
            preserve_default=False,
        ),
    ]
