# Generated by Django 2.1.7 on 2019-04-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0050_auto_20190411_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('standard_left_header.html', 'standard left header'), ('survey_centered_header.html', 'survey centered header')], max_length=50, verbose_name='featured template'),
        ),
    ]
