# Generated by Django 2.1.7 on 2019-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0053_section_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='active',
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('', '')], max_length=50, verbose_name='standard template'),
        ),
    ]
