# Generated by Django 2.1.7 on 2019-04-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0055_auto_20190413_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_features', to='landing.Presentation'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_features', to='landing.Section'),
        ),
    ]
