# Generated by Django 2.1.7 on 2019-04-15 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190411_0806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0056_auto_20190413_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='products',
            field=models.ManyToManyField(null=True, related_name='product_features', to='products.Product'),
        ),
        migrations.AddField(
            model_name='feature',
            name='users',
            field=models.ManyToManyField(null=True, related_name='user_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
