# Generated by Django 2.1.7 on 2019-04-15 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0015_auto_20190411_0806'),
        ('landing', '0059_auto_20190415_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='products',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='users',
        ),
        migrations.AddField(
            model_name='section',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_features', to='products.Product'),
        ),
        migrations.AddField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
