# Generated by Django 2.1.7 on 2019-04-18 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0060_auto_20190415_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
