# Generated by Django 2.1.7 on 2019-04-19 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0039_auto_20190411_0806'),
        ('landing', '0061_auto_20190418_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey', to='feedbacks.Survey', verbose_name='survey'),
        ),
        migrations.AlterField(
            model_name='section',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='section',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
