# Generated by Django 2.1.7 on 2019-04-19 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0062_auto_20190419_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='section',
            name='featured_label',
        ),
        migrations.RemoveField(
            model_name='section',
            name='featured_link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='presentation',
        ),
    ]
