# Generated by Django 2.1.7 on 2019-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0064_auto_20190419_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presentation',
        ),
        migrations.AlterField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('standard_left_header.html', 'standard left header'), ('standard_centered_header.html', 'standard centered header')], max_length=50, verbose_name='featured template'),
        ),
    ]
