# Generated by Django 2.1.7 on 2019-04-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190411_0806'),
        ('landing', '0065_auto_20190419_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='blog.Article', verbose_name='article'),
        ),
    ]
