# Generated by Django 2.1.7 on 2019-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0067_auto_20190421_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_centered.html', 'standard centered section'), ('section_left.html', 'standard left section')], max_length=50, verbose_name='standard template'),
        ),
    ]
