# Generated by Django 2.1.7 on 2019-04-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0068_auto_20190421_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_centered.html', 'standard centered section'), ('section_left.html', 'standard left section'), ('section_right.html', 'standard right section')], max_length=50, verbose_name='standard template'),
        ),
    ]
