# Generated by Django 2.1.7 on 2019-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0069_auto_20190421_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='dark mode'),
            preserve_default=False,
        ),
    ]
