# Generated by Django 2.1.7 on 2019-04-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0070_section_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='alignment',
            field=models.CharField(choices=[('left', 'left'), ('centered', 'centered'), ('right', 'right')], default='left', max_length=50, verbose_name='alignment'),
            preserve_default=False,
        ),
    ]
