# Generated by Django 2.1.7 on 2019-04-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0071_section_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('standard_header.html', 'standard header')], max_length=50, verbose_name='featured template'),
        ),
    ]
