# Generated by Django 2.1.7 on 2019-04-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0072_auto_20190423_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('standard_section.html', 'standard section')], max_length=50, verbose_name='standard template'),
        ),
    ]
