# Generated by Django 2.2.1 on 2019-05-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0075_auto_20190524_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color'),
        ),
    ]
