# Generated by Django 2.2.2 on 2019-06-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190411_0806'),
        ('landing', '0076_auto_20190524_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_article',
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.Article', verbose_name='articles'),
        ),
    ]
