# Generated by Django 2.2.10 on 2020-02-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0077_auto_20190618_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('standard_header.html', 'standard header'), ('search_header.html', 'search header')], max_length=50, verbose_name='featured template'),
        ),
    ]
