# Generated by Django 2.2.10 on 2020-02-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0078_auto_20200215_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('standard_section.html', 'standard section'), ('cards_section.html', 'cards section')], max_length=50, verbose_name='standard template'),
        ),
    ]
