# Generated by Django 2.2.10 on 2020-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0079_auto_20200215_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='alignment',
            field=models.CharField(choices=[('left', 'left'), ('centered', 'centered'), ('right', 'right')], default='left', max_length=50, verbose_name='alignment'),
        ),
    ]
