# Generated by Django 2.2.10 on 2020-03-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0080_auto_20200301_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='alignment',
            field=models.CharField(choices=[('left', 'left'), ('centered', 'centered'), ('right', 'right')], default='centered', max_length=50, verbose_name='alignment'),
        ),
    ]
