# Generated by Django 2.2.10 on 2020-03-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0081_auto_20200301_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='featured_template',
            field=models.CharField(choices=[('header_standard.html', 'standard header'), ('header_search.html', 'search header')], max_length=50, verbose_name='featured template'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_standard.html', 'standard section'), ('section_plain.html', 'plain section')], max_length=50, verbose_name='standard template'),
        ),
    ]
