# Generated by Django 2.2.13 on 2020-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0086_auto_20200718_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='story',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
