# Generated by Django 2.2.13 on 2020-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0087_auto_20200718_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video',
            field=models.URLField(blank=True, verbose_name='video'),
        ),
    ]
