# Generated by Django 2.2.13 on 2020-07-19 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0088_section_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='landing.Section'),
        ),
    ]
