# Generated by Django 2.2.13 on 2020-08-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0090_searchsuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
