# Generated by Django 2.2.13 on 2020-08-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0091_delete_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(choices=[(1, 'text first'), (3, 'test second')], default=1, verbose_name='text position'),
        ),
    ]
