# Generated by Django 2.2.13 on 2020-08-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0092_section_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='dark mode'),
        ),
    ]
