# Generated by Django 2.2.24 on 2021-08-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0103_policyarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='prefix',
            field=models.TextField(blank=True, verbose_name='prefix text'),
        ),
    ]
