# Generated by Django 2.2.24 on 2021-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0105_auto_20210816_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='articles',
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.BooleanField(default=False, help_text='Show the latest articles', verbose_name='articles'),
        ),
    ]
