# Generated by Django 2.2.24 on 2022-01-22 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20211024_1100'),
        ('products', '0075_product_hot'),
        ('landing', '0109_auto_20220121_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='about_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='landing.AboutArticle', verbose_name='about article'),
        ),
        migrations.AddField(
            model_name='section',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='blog.ArticleCategory', verbose_name='product category'),
        ),
        migrations.AddField(
            model_name='section',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='products.ProductCategory', verbose_name='product category'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='button label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button label'),
        ),
        migrations.AlterField(
            model_name='section',
            name='button_label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='button label'),
        ),
    ]
