# Generated by Django 2.2.24 on 2022-01-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0110_auto_20220122_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='blog.ArticleCategory', verbose_name='article category'),
        ),
    ]
