# Generated by Django 2.2.24 on 2022-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0111_auto_20220122_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attachment_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='attachment label'),
        ),
    ]
