# Generated by Django 2.2.24 on 2022-01-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0112_section_attachment_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attachment_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='attachment label'),
        ),
        migrations.AddField(
            model_name='section',
            name='attachment_label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='attachment label'),
        ),
    ]
