# Generated by Django 2.2.28 on 2022-09-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0113_auto_20220124_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='about_article',
        ),
        migrations.RemoveField(
            model_name='section',
            name='article_category',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attachment_label',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attachment_label_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attachment_label_it',
        ),
        migrations.RemoveField(
            model_name='section',
            name='product_category',
        ),
    ]
