# Generated by Django 2.2.28 on 2022-10-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0114_auto_20220917_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutarticle',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='aboutarticle',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
