# Generated by Django 2.2.28 on 2022-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0116_auto_20221010_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policyarticle',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='slug_it',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='policyarticle',
            name='title_it',
        ),
        migrations.AddField(
            model_name='section',
            name='attachment_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='attachment label'),
        ),
        migrations.AddField(
            model_name='section',
            name='attachment_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='attachment label'),
        ),
        migrations.AddField(
            model_name='section',
            name='attachment_label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='attachment label'),
        ),
    ]
