# Generated by Django 2.2.28 on 2022-11-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0117_auto_20221010_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='featured_video',
            field=models.BooleanField(default=False, verbose_name='featured video'),
        ),
    ]
