# Generated by Django 2.2.28 on 2022-11-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0118_section_featured_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video_image',
            field=models.URLField(blank=True, verbose_name='video image'),
        ),
    ]
