# Generated by Django 2.2.28 on 2022-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0119_section_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='video_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='video label'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='video label'),
        ),
        migrations.AddField(
            model_name='section',
            name='video_label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='video label'),
        ),
    ]
