# Generated by Django 2.2.28 on 2022-11-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0120_auto_20221106_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='featured_video',
        ),
        migrations.RemoveField(
            model_name='section',
            name='video_label',
        ),
        migrations.RemoveField(
            model_name='section',
            name='video_label_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='video_label_it',
        ),
    ]
