# Generated by Django 2.2.28 on 2024-01-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0126_auto_20240102_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutarticle',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AddField(
            model_name='policyarticle',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AddField(
            model_name='searchsuggestion',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
    ]
