# Generated by Django 2.2.28 on 2025-01-19 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0129_auto_20250119_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='cover_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sections', to='landing.SectionImage', verbose_name='secondary cover'),
        ),
    ]
