# Generated by Django 2.2.28 on 2025-01-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0130_auto_20250119_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionimage',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='sectionimage',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
    ]
