# Generated by Django 2.2.28 on 2025-12-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0131_auto_20250119_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cover_secondary',
        ),
    ]
