# Generated by Django 2.2.28 on 2025-12-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0132_remove_section_cover_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='cover_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_sections', to='landing.SectionImage', verbose_name='secondary cover'),
        ),
    ]
