# Generated by Django 2.2.28 on 2025-12-31 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190430_1532'),
        ('landing', '0133_section_cover_secondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('publishablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel')),
            ],
            options={
                'verbose_name': 'landing page',
                'verbose_name_plural': 'landing pages',
            },
            bases=('core.publishablemodel',),
        ),
        migrations.AlterModelOptions(
            name='sectionimage',
            options={'verbose_name': 'section image', 'verbose_name_plural': 'section images'},
        ),
    ]
