# Generated by Django 2.2.28 on 2025-12-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0134_auto_20251231_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landingpage',
            options={'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AddField(
            model_name='landingpage',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Light gray'), ('gray', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('cyan', 'Cyan')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title',
            field=models.CharField(default='', max_length=80, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
    ]
