# Generated by Django 2.2.28 on 2025-12-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0135_auto_20251231_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
