# Generated by Django 2.2.28 on 2025-12-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0137_auto_20251231_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='enable_featured_content',
            field=models.BooleanField(default=True, verbose_name='enable featured content'),
        ),
    ]
