# Generated by Django 2.2.28 on 2025-12-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0138_landingpage_enable_featured_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
