# Generated by Django 2.2.28 on 2025-12-31 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0139_auto_20251231_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='landing.LandingPage', verbose_name='landing page'),
        ),
    ]
