# Generated by Django 2.2.28 on 2025-12-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0140_section_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='landing_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='landing.LandingPage', verbose_name='landing page'),
        ),
    ]
