# Generated by Django 2.2.28 on 2025-12-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0142_auto_20251231_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='section',
            name='landing_pages',
            field=models.ManyToManyField(blank=True, related_name='sections', to='landing.LandingPage', verbose_name='landing pages'),
        ),
    ]
