# Generated by Django 2.2.28 on 2025-12-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0143_auto_20251231_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='landing_pages',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='landing_pages', to='landing.Section', verbose_name='sections'),
        ),
    ]
