# Generated by Django 2.2.28 on 2026-01-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0144_auto_20251231_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='enable_signin',
            field=models.BooleanField(default=True, verbose_name='enable sign in section'),
        ),
    ]
