# Generated by Django 2.2.28 on 2026-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0145_landingpage_enable_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured objects are displayed on the top of their page. If pinned, they are also displayed on the top of the landing page', verbose_name='featured'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned objects appear on the navbar and on the landing page', verbose_name='pinned'),
        ),
    ]
