# Generated by Django 2.2.28 on 2026-01-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0146_auto_20260102_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='theme',
            field=models.CharField(blank=True, choices=[(0, 'quick'), (1, 'onepage')], default=0, max_length=30, verbose_name='theme'),
        ),
    ]
