# Generated by Django 2.2.28 on 2026-01-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0147_landingpage_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.PositiveIntegerField(choices=[(0, 'quick'), (1, 'onepage')], default=0, verbose_name='theme'),
        ),
    ]
