# Generated by Django 2.2.28 on 2026-01-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0149_auto_20260102_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.CharField(choices=[('landing/landing_quick.html', 'quick classic'), ('landing/landing_onepage_quick.html', 'quick onepage'), ('landing/landing_onepage.html', 'custom onepage')], default='landing/landing_quick.html', max_length=30, verbose_name='theme'),
        ),
    ]
