# Generated by Django 2.2.28 on 2026-01-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0151_auto_20260102_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='theme',
            field=models.CharField(choices=[('landing/landing_quick.html', 'quick classic'), ('landing/landing_quick_onepage.html', 'quick onepage'), ('landing/landing_custom_onepage.html', 'custom onepage')], default='landing/landing_quick.html', max_length=50, verbose_name='theme'),
        ),
    ]
