# Generated by Django 2.2.28 on 2026-01-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0152_auto_20260102_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='attachment_label',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attachment_label_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='attachment_label_it',
        ),
        migrations.AddField(
            model_name='section',
            name='attached_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.Section', verbose_name='attached section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='attached_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='attached product'),
        ),
    ]
