# Generated by Django 2.2.28 on 2026-01-04 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0153_auto_20260104_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='attached_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='section',
            name='attached_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.Section', verbose_name='section'),
        ),
    ]
