# Generated by Django 2.2.28 on 2026-01-04 15:25

from django.db import migrations, models
from django.template.defaultfilters import slugify

def update_slug(apps, schema_editor):
    Section = apps.get_model('landing', 'Section')
    for s in Section.objects.all():
        if s.title_it:
            s.slug_it = slugify(s.title_it)
        if s.title_en:
            s.slug_en = slugify(s.title_en)
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0154_auto_20260104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.RunPython(update_slug),    
    ]
