# Generated by Django 2.2.28 on 2026-01-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0157_auto_20260104_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='enable_featured_content',
        ),
        migrations.AddField(
            model_name='landingpage',
            name='enable_pinned_content',
            field=models.BooleanField(default=True, verbose_name='enable pinned content'),
        ),
    ]
