# Generated by Django 2.2.28 on 2026-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0160_auto_20260105_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='prefix',
            field=models.TextField(blank=True, verbose_name='prefix text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='prefix_en',
            field=models.TextField(blank=True, null=True, verbose_name='prefix text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='prefix_it',
            field=models.TextField(blank=True, null=True, verbose_name='prefix text'),
        ),
        migrations.AddField(
            model_name='feature',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='feature',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='feature',
            name='subtitle_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
