# Generated by Django 2.2.28 on 2026-01-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0161_auto_20260105_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='short_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='section',
            name='short_description_it',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
    ]
