# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0162_auto_20260106_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutarticle',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='policyarticle',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='searchsuggestion',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
    ]
