# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0163_auto_20260301_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutarticle',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='policyarticle',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='searchsuggestion',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
    ]
