# Generated by Django 2.2.28 on 2026-08-29 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0164_auto_20260301_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
