# Generated by Django 2.2.28 on 2026-08-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0045_auto_20220917_1105'),
        ('landing', '0165_auto_20260829_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attached_survey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='feedbacks.Survey', verbose_name='survey'),
        ),
    ]
