# Generated by Django 2.2.28 on 2026-08-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0023_sectionaddon'),
        ('landing', '0166_section_attached_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='attached_addon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='geminigm.SectionAddon', verbose_name='addon'),
        ),
    ]
