# Generated by Django 2.2.13 on 2020-06-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0002_auto_20200610_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='TooltipGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='default', max_length=30, verbose_name='color')),
            ],
            options={
                'verbose_name': 'tooltip group',
                'verbose_name_plural': 'tooltip groups',
            },
        ),
        migrations.AddField(
            model_name='tooltip',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooltips', to='tooltips.TooltipGroup'),
        ),
    ]
