# Generated by Django 2.2.13 on 2020-06-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0003_auto_20200612_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltipgroup',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='tooltipgroup',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
