# Generated by Django 2.2.13 on 2020-06-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0004_auto_20200612_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooltip',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
