# Generated by Django 2.2.13 on 2020-06-12 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0106_auto_20200524_1227'),
        ('tooltips', '0005_auto_20200612_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltip',
            name='books',
            field=models.ManyToManyField(to='ebooks.Book', verbose_name='book'),
        ),
        migrations.AlterField(
            model_name='tooltip',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tooltips', to='tooltips.TooltipGroup', verbose_name='group'),
        ),
    ]
