# Generated by Django 2.2.16 on 2020-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0015_auto_20200901_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltip',
            name='paper_mention_link',
            field=models.URLField(default='', verbose_name='link menzione'),
            preserve_default=False,
        ),
    ]
