# Generated by Django 2.2.16 on 2020-10-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0016_tooltip_paper_mention_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltip',
            name='paper_mention_link',
            field=models.URLField(verbose_name='mention link'),
        ),
    ]
