# Generated by Django 2.2.28 on 2024-01-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tooltips', '0019_auto_20240102_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooltip',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Light gray'), ('gray', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('cyan', 'Cyan')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='tooltipgroup',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Light gray'), ('gray', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('cyan', 'Cyan')], default='default', max_length=30, verbose_name='color'),
        ),
    ]
