# Generated by Django 2.1.7 on 2019-04-24 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_auto_20190424_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='section',
            name='content_it',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
    ]
