# Generated by Django 2.1.7 on 2019-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
