# Generated by Django 2.1.7 on 2019-04-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0018_delete_section'),
        ('ebooks', '0005_auto_20190425_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('publishablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('icon', models.CharField(max_length=30, verbose_name='icon')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('color', models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color')),
                ('order_index', models.PositiveIntegerField(verbose_name='order index')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('chapter_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
            },
            bases=('core.publishablemodel', models.Model),
        ),
        migrations.RemoveField(
            model_name='section',
            name='product',
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.Chapter', verbose_name='chapter'),
        ),
    ]
