# Generated by Django 2.1.7 on 2019-04-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0007_auto_20190429_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='ebooks.Chapter', verbose_name='chapter'),
        ),
    ]
