# Generated by Django 2.1.7 on 2019-04-30 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ebooks', '0008_auto_20190429_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('publishablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('icon', models.CharField(max_length=30, verbose_name='icon')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('description_it', models.TextField(null=True, verbose_name='description')),
                ('description_en', models.TextField(null=True, verbose_name='description')),
                ('color', models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('slug_it', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
            bases=('core.publishablemodel', models.Model),
        ),
    ]
