# Generated by Django 2.1.7 on 2019-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0010_chapter_chapter_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_title',
            field=models.CharField(default='PC', max_length=2, verbose_name='short title'),
            preserve_default=False,
        ),
    ]
