# Generated by Django 2.1.7 on 2019-05-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0012_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_product',
        ),
    ]
