# Generated by Django 2.1.7 on 2019-05-03 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_delete_section'),
        ('ebooks', '0013_remove_chapter_chapter_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='product'),
        ),
    ]
