# Generated by Django 2.1.7 on 2019-05-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0015_remove_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='ebooks.Book', verbose_name='book'),
        ),
    ]
