# Generated by Django 2.1.7 on 2019-05-05 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0016_auto_20190505_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='products.Product', verbose_name='product'),
        ),
    ]
