# Generated by Django 2.1.7 on 2019-05-15 05:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0017_auto_20190505_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('icon', models.CharField(max_length=30, verbose_name='icon')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('color', models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color')),
                ('order_index', models.PositiveIntegerField(verbose_name='order index')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'universal section',
                'verbose_name_plural': 'universal sections',
            },
        ),
    ]
