# Generated by Django 2.1.7 on 2019-05-15 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0018_universalsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='universal_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='ebooks.UniversalSection', verbose_name='universal section'),
        ),
    ]
