# Generated by Django 2.1.7 on 2019-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0019_section_universal_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='overwrite',
            field=models.BooleanField(default=False, verbose_name='overwrite'),
            preserve_default=False,
        ),
    ]
