# Generated by Django 2.1.7 on 2019-05-15 06:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0020_section_overwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='universalsection',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='universalsection',
            name='content_it',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='universalsection',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='universalsection',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='universalsection',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='universalsection',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
