# Generated by Django 2.1.7 on 2019-05-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0021_auto_20190515_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universalsection',
            options={'verbose_name': 'universal Section', 'verbose_name_plural': 'universal Sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug_it',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_it',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='content_it',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='description_it',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='universalsection',
            name='title_it',
        ),
    ]
