# Generated by Django 2.1.7 on 2019-05-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0023_auto_20190515_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='internal_order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='internal order index'),
            preserve_default=False,
        ),
    ]
