# Generated by Django 2.1.7 on 2019-05-16 05:33

from django.db import migrations, models


def forwards(apps, schema_editor):
    user_model = apps.get_model('ebooks', 'Section')
    for obj in user_model.objects.all():
        obj.internal_order_index = internal_order_index = int(f'{obj.chapter.order_index}{obj.order_index}')
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0024_section_internal_order_index'),
    ]

    operations = [
        migrations.RunPython(
            forwards, 
            reverse_code=migrations.RunPython.noop
        ),
    ]
