# Generated by Django 2.1.7 on 2019-05-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0025_initialize_section_interal_oder_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='overwrite',
        ),
    ]
