# Generated by Django 2.2.1 on 2019-05-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0031_auto_20190521_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='col_lg',
            field=models.PositiveIntegerField(choices=[(12, 'Full'), (6, 'Half'), (4, 'Quarter')], default=12, verbose_name='lg column'),
        ),
    ]
