# Generated by Django 2.2.1 on 2019-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0033_section_col_md'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='section',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
