# Generated by Django 2.2.1 on 2019-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0034_auto_20190523_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='text_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20, verbose_name='text alignment'),
        ),
    ]
