# Generated by Django 2.2.1 on 2019-05-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0039_auto_20190526_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='col_lg',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='lg column'),
        ),
        migrations.AddField(
            model_name='book',
            name='col_md',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='md column'),
        ),
    ]
