# Generated by Django 2.2.1 on 2019-05-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0040_auto_20190526_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Section category',
                'verbose_name_plural': 'Section categories',
            },
        ),
    ]
