# Generated by Django 2.2.1 on 2019-05-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0041_sectioncategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.SectionCategory', verbose_name='category'),
        ),
    ]
