# Generated by Django 2.2.1 on 2019-05-31 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0042_section_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectioncategory',
            name='title_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sectioncategory',
            name='title_it',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.SectionCategory', verbose_name='category'),
        ),
    ]
