# Generated by Django 2.2.1 on 2019-05-31 05:55

import diventi.ebooks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0043_auto_20190531_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.ForeignKey(default=diventi.ebooks.models.SectionCategory.get_default_category, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ebooks.SectionCategory', verbose_name='category'),
        ),
    ]
