# Generated by Django 2.2.1 on 2019-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0044_auto_20190603_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='super_title',
            field=models.BooleanField(default=True, verbose_name='super title'),
        ),
    ]
