# Generated by Django 2.2.1 on 2019-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0045_auto_20190603_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='card_type',
            field=models.CharField(blank=True, choices=[('card-testimonial', 'testimonial'), ('card-plain', 'plain')], max_length=30, null=True, verbose_name='card_type'),
        ),
    ]
