# Generated by Django 2.2.1 on 2019-06-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0046_section_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('standard_section.html', 'standard section')], default='standard_section.html', max_length=50, verbose_name='standard template'),
        ),
        migrations.AlterField(
            model_name='section',
            name='card_type',
            field=models.CharField(blank=True, choices=[('card-testimonial', 'testimonial'), ('card-plain', 'plain')], max_length=30, null=True, verbose_name='card type'),
        ),
    ]
