# Generated by Django 2.2.1 on 2019-06-05 06:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0049_auto_20190605_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universalsection',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='content_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
