# Generated by Django 2.2.1 on 2019-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0050_auto_20190605_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_standard.html', 'standard section'), ('section_with_icon.html', 'section with icon')], default='section_standard.html', max_length=50, verbose_name='standard template'),
        ),
    ]
