# Generated by Django 2.2.1 on 2019-06-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0051_auto_20190611_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='card_type',
            field=models.CharField(choices=[('', 'normal'), ('card-plain', 'plain'), ('card-testimonial', 'testimonial')], default='', max_length=30, verbose_name='card type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_standard.html', 'standard'), ('section_with_icon.html', 'with icon'), ('section_with_image.html', 'with image')], default='section_standard.html', max_length=50, verbose_name='template'),
        ),
    ]
