# Generated by Django 2.2.1 on 2019-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0053_auto_20190612_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='card_type',
            field=models.CharField(choices=[(' ', 'standard'), ('card-plain', 'no background')], default=' ', max_length=30, verbose_name='card type'),
        ),
    ]
