# Generated by Django 2.2.2 on 2019-06-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0054_auto_20190612_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='Section',
            name='slug',
            field=models.SlugField(unique=True, null=True, verbose_name='slug'),
        ),
    ]
