# Generated by Django 2.2.2 on 2019-06-15 10:26

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0054_auto_20190612_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='section',
            name='card_type',
            field=models.CharField(choices=[(' ', 'Standard'), ('card-plain', 'No background')], default=' ', max_length=30, verbose_name='card type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.CharField(choices=[('section_standard.html', 'Standard'), ('section_with_icon.html', 'With icon'), ('section_with_image.html', 'With image')], default='section_standard.html', max_length=50, verbose_name='template'),
        ),
    ]
