# Generated by Django 2.2.2 on 2019-06-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0056_auto_20190615_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bookmark',
            field=models.BooleanField(default=True, verbose_name='bookmark'),
        ),
    ]
