# Generated by Django 2.2.2 on 2019-06-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0059_auto_20190617_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='ebooks.Section', verbose_name='section'),
        ),
    ]
