# Generated by Django 2.2.2 on 2019-06-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0061_characterrelationships_charactersheet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterRelationships',
        ),
        migrations.DeleteModel(
            name='CharacterSheet',
        ),
    ]
