# Generated by Django 2.2.3 on 2019-08-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0063_book_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subtitle',
            field=models.TextField(default='', verbose_name='subtitle'),
            preserve_default=False,
        ),
    ]
