# Generated by Django 2.2.3 on 2019-08-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0064_book_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='subtitle',
        ),
    ]
