# Generated by Django 2.2.3 on 2019-08-04 16:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0065_remove_book_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=ckeditor.fields.RichTextField(default='test', verbose_name='summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='summary_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='summary'),
        ),
        migrations.AddField(
            model_name='book',
            name='summary_it',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='summary'),
        ),
    ]
