# Generated by Django 2.2.3 on 2019-08-04 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0066_auto_20190804_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lead',
            field=ckeditor.fields.RichTextField(default='', verbose_name='lead'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='lead_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='lead'),
        ),
        migrations.AddField(
            model_name='book',
            name='lead_it',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='lead'),
        ),
    ]
