# Generated by Django 2.2.3 on 2019-08-04 16:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0067_auto_20190804_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lead',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lead_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lead_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='lead'),
        ),
    ]
