# Generated by Django 2.2.3 on 2019-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0070_auto_20190804_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
