# Generated by Django 2.2.4 on 2019-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0075_auto_20190811_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bookmark',
            field=models.BooleanField(default=True, verbose_name='bookmark'),
        ),
    ]
