# Generated by Django 2.2.4 on 2019-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0078_auto_20191006_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='part_book',
        ),
        migrations.AddField(
            model_name='book',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='books', to='ebooks.Part', verbose_name='parts'),
        ),
    ]
