# Generated by Django 2.2.4 on 2019-10-06 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0080_remove_book_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='ebooks.Part', verbose_name='part'),
        ),
    ]
