# Generated by Django 2.2.4 on 2019-10-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0081_auto_20191006_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
                ('initial_string', models.CharField(max_length=30, verbose_name='initial string')),
                ('initial_string_it', models.CharField(max_length=30, null=True, verbose_name='initial string')),
                ('initial_string_en', models.CharField(max_length=30, null=True, verbose_name='initial string')),
                ('result_string', models.CharField(max_length=30, verbose_name='result string')),
                ('result_string_it', models.CharField(max_length=30, null=True, verbose_name='result string')),
                ('result_string_en', models.CharField(max_length=30, null=True, verbose_name='result string')),
            ],
            options={
                'verbose_name': 'app rule',
                'verbose_name_plural': 'app rules',
            },
        ),
    ]
