# Generated by Django 2.2.4 on 2019-10-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0082_apprule'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='rule',
            field=models.ManyToManyField(to='ebooks.AppRule'),
        ),
    ]
