# Generated by Django 2.2.4 on 2019-10-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0083_section_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='rule',
            new_name='rules',
        ),
    ]
