# Generated by Django 2.2.4 on 2019-10-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0084_auto_20191022_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='rules',
            field=models.ManyToManyField(blank=True, to='ebooks.AppRule'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
