# Generated by Django 2.2.4 on 2019-10-23 05:31

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('ebooks', '0085_auto_20191022_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppRule',
            new_name='ReplacementRule',
        ),
        migrations.AlterModelOptions(
            name='replacementrule',
            options={'verbose_name': 'replacement rule', 'verbose_name_plural': 'replacement rules'},
        ),
    ]
