# Generated by Django 2.2.8 on 2019-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0087_auto_20191105_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='slug_it',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
