# Generated by Django 2.2.10 on 2020-03-15 10:27

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0088_auto_20191228_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='content2'),
        ),
    ]
