# Generated by Django 2.2.10 on 2020-03-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0089_section_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='content2',
        ),
    ]
