# Generated by Django 2.2.10 on 2020-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0090_remove_section_content2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_it',
            field=models.TextField(blank=True, null=True, verbose_name='content2'),
        ),
    ]
