# Generated by Django 2.2.10 on 2020-03-15 11:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0091_auto_20200315_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content2',
            field=models.TextField(blank=True, verbose_name='content2'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
