# Generated by Django 2.2.12 on 2020-04-13 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0093_remove_section_content2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-order_index'], 'verbose_name': 'chapter', 'verbose_name_plural': 'chapters'},
        ),
    ]
