# Generated by Django 2.2.12 on 2020-04-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0094_auto_20200413_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['-order_index'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
    ]
