# Generated by Django 2.2.12 on 2020-04-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0095_auto_20200415_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
                ('aspect_type', models.CharField(choices=[('location', 'Location aspect'), ('adventure', 'Adventure aspect'), ('campaign', 'Campaign aspect')], max_length=20, verbose_name='ring of storytelling')),
                ('secction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_aspects', to='ebooks.Section', verbose_name='section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
