# Generated by Django 2.2.12 on 2020-04-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0096_sectionaspect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionaspect',
            options={'verbose_name': 'section aspect', 'verbose_name_plural': 'section aspects'},
        ),
        migrations.AlterField(
            model_name='sectionaspect',
            name='aspect_type',
            field=models.CharField(choices=[('location', 'Location aspects'), ('adventure', 'Adventure aspects'), ('campaign', 'Campaign aspects')], max_length=20, verbose_name='aspect type'),
        ),
    ]
