# Generated by Django 2.2.12 on 2020-05-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0097_auto_20200419_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('title_it', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_it', models.TextField(blank=True, null=True, verbose_name='description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
                ('secret_type', models.CharField(choices=[('treasure', 'Treasure'), ('trap', 'Trap'), ('revelation', 'Revelation')], max_length=20, verbose_name='sercret type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='ebooks.Section', verbose_name='section')),
            ],
            options={
                'verbose_name': 'secret',
                'verbose_name_plural': 'secrets',
            },
        ),
    ]
