# Generated by Django 2.2.12 on 2020-05-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0099_auto_20200502_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionaspect',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='ebooks.Section', verbose_name='section'),
        ),
    ]
