# Generated by Django 2.2.12 on 2020-05-03 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0102_auto_20200502_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_it',
        ),
        migrations.AddField(
            model_name='section',
            name='situation',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This content should be read by game master's eyes only.", verbose_name='situation'),
        ),
        migrations.AddField(
            model_name='section',
            name='situation_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This content should be read by game master's eyes only.", null=True, verbose_name='situation'),
        ),
        migrations.AddField(
            model_name='section',
            name='situation_it',
            field=ckeditor.fields.RichTextField(blank=True, help_text="This content should be read by game master's eyes only.", null=True, verbose_name='situation'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content should be simple to read aloud by our fellow game masters.', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content should be simple to read aloud by our fellow game masters.', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_it',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content should be simple to read aloud by our fellow game masters.', null=True, verbose_name='content'),
        ),
    ]
