# Generated by Django 2.2.12 on 2020-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0103_auto_20200503_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='requires_skill_check',
            field=models.BooleanField(default=True, verbose_name='requires a skill check'),
        ),
    ]
