# Generated by Django 2.2.12 on 2020-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0104_secret_requires_skill_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='col_lg',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (8, 'Three fourths'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='lg column'),
        ),
        migrations.AlterField(
            model_name='book',
            name='col_md',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (8, 'Three fourths'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='md column'),
        ),
        migrations.AlterField(
            model_name='section',
            name='col_lg',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (8, 'Three fourths'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='lg column'),
        ),
        migrations.AlterField(
            model_name='section',
            name='col_md',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (8, 'Three fourths'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='md column'),
        ),
    ]
