# Generated by Django 2.2.13 on 2020-06-14 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0107_auto_20200614_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content will appear as a brief tooltip thought the book.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content will appear as a brief tooltip thought the book.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content will appear as a brief tooltip thought the book.', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, help_text='This content will appear as a brief tooltip thought the book.', null=True, verbose_name='description'),
        ),
    ]
