# Generated by Django 2.2.13 on 2020-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0113_auto_20200830_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='replacementrule',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='replacementrule',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='replacementrule',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sectionaspect',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sectionaspect',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='sectionaspect',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
