# Generated by Django 2.2.16 on 2020-09-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0114_auto_20200901_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='template',
            field=models.CharField(choices=[('quick', 'Quick'), ('web', 'Web'), ('material', 'Material')], default='quick', max_length=50, verbose_name='template'),
        ),
    ]
