# Generated by Django 2.2.16 on 2020-09-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0115_auto_20200921_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paper_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
    ]
