# Generated by Django 2.2.16 on 2020-09-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0116_book_paper_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paper_id_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
        migrations.AddField(
            model_name='book',
            name='paper_id_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
    ]
