# Generated by Django 2.2.16 on 2020-10-05 20:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0120_auto_20201005_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='summary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='summary'),
        ),
    ]
