# Generated by Django 2.2.16 on 2020-10-05 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0121_auto_20201005_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lead_en',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lead_it',
        ),
    ]
