# Generated by Django 2.2.28 on 2024-01-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0130_auto_20240127_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='logo_background',
        ),
    ]
