# Generated by Django 2.2.28 on 2024-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0131_remove_book_logo_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_file_url',
            field=models.URLField(blank=True, verbose_name='content file url'),
        ),
    ]
