# Generated by Django 2.2.28 on 2024-01-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0132_book_content_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_file_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='content file url'),
        ),
        migrations.AddField(
            model_name='book',
            name='content_file_url_it',
            field=models.URLField(blank=True, null=True, verbose_name='content file url'),
        ),
    ]
