# Generated by Django 2.2.28 on 2024-01-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0133_auto_20240127_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content_file_url',
            field=models.URLField(blank=True, verbose_name='file url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_file_url_en',
            field=models.URLField(blank=True, null=True, verbose_name='file url'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content_file_url_it',
            field=models.URLField(blank=True, null=True, verbose_name='file url'),
        ),
    ]
