# Generated by Django 2.2.28 on 2024-02-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0135_remove_book_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_en',
            field=models.URLField(blank=True, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='book',
            name='image_it',
            field=models.URLField(blank=True, null=True, verbose_name='image'),
        ),
    ]
