# Generated by Django 2.2.28 on 2025-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0138_auto_20250404_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paper_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
    ]
