# Generated by Django 2.2.28 on 2025-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0140_auto_20250404_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paper_id_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
        migrations.AddField(
            model_name='book',
            name='paper_id_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='paper id'),
        ),
    ]
