# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0142_auto_20260105_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='replacementrule',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='sectionaspect',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='universalsection',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
    ]
