# Generated by Django 2.2.12 on 2020-04-26 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0002_auto_20200425_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antagonist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
            ],
            options={
                'verbose_name': 'Antagonist',
                'verbose_name_plural': 'Antagonists',
            },
        ),
        migrations.AlterField(
            model_name='adventure',
            name='ring',
            field=models.CharField(choices=[('first', 'First Ring'), ('second', 'Second Ring'), ('third', 'Third Ring')], help_text='Any adventure should have at least one ring of each type.', max_length=20, verbose_name='ring of storytelling'),
        ),
        migrations.AddField(
            model_name='situation',
            name='antagonist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to='adventures.Antagonist', verbose_name='antagonist'),
        ),
    ]
