# Generated by Django 2.2.12 on 2020-04-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_auto_20200416_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='resolution',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('mixed', 'Mixed')], max_length=20, verbose_name='resolution'),
        ),
    ]
