# Generated by Django 2.2.12 on 2020-04-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0003_auto_20200426_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='antagonist',
        ),
        migrations.AddField(
            model_name='adventure',
            name='antagonist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situations', to='adventures.Antagonist', verbose_name='antagonist'),
        ),
    ]
