# Generated by Django 2.2.12 on 2020-04-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_auto_20200416_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
                ('outcome', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('mixed', 'Mixed')], max_length=20, verbose_name='outcome')),
            ],
            options={
                'verbose_name': 'Resolution',
                'verbose_name_plural': 'Resolutions',
            },
        ),
        migrations.AlterField(
            model_name='story',
            name='resolution',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('danger', 'Failure'), ('default', 'Mixed')], max_length=20, verbose_name='resolution'),
        ),
    ]
