# Generated by Django 2.2.12 on 2020-04-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0004_auto_20200426_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='navigation',
            field=models.CharField(choices=[('exploration', 'Exploration')], default='exploration', max_length=20, verbose_name='navigation'),
        ),
    ]
