# Generated by Django 2.2.12 on 2020-04-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_auto_20200418_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='adventures.Resolution'),
        ),
    ]
