# Generated by Django 2.2.12 on 2020-05-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0005_story_navigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='antagonist',
        ),
        migrations.AlterField(
            model_name='story',
            name='navigation',
            field=models.CharField(choices=[('situation_random', 'Exploration')], default='situation_random', max_length=20, verbose_name='navigation'),
        ),
        migrations.CreateModel(
            name='AntagonistGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color')),
                ('level', models.PositiveIntegerField(verbose_name='level')),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Adventure', verbose_name='adventure')),
                ('antagonist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adventures.Antagonist', verbose_name='antagonist')),
            ],
            options={
                'verbose_name': 'Antagonist Goal',
                'verbose_name_plural': 'Antagonist Goals',
            },
        ),
        migrations.AddField(
            model_name='adventure',
            name='antagonist',
            field=models.ManyToManyField(blank=True, through='adventures.AntagonistGoal', to='adventures.Antagonist', verbose_name='players'),
        ),
    ]
