# Generated by Django 2.2.12 on 2020-04-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0006_auto_20200418_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='outcome',
        ),
    ]
