# Generated by Django 2.2.12 on 2020-05-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_auto_20200502_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='antagonist',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='antagonist',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
