# Generated by Django 2.2.12 on 2020-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0007_remove_resolution_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
