# Generated by Django 2.2.12 on 2020-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_auto_20200502_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='warning', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='antagonist',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='warning', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='warning', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='warning', max_length=30, verbose_name='color'),
        ),
    ]
