# Generated by Django 2.2.12 on 2020-04-18 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0008_auto_20200418_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situation',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='next_situation',
        ),
        migrations.AddField(
            model_name='story',
            name='next_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.Story'),
        ),
        migrations.AddField(
            model_name='story',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='adventures.Situation'),
        ),
    ]
