# Generated by Django 2.2.12 on 2020-04-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0009_auto_20200418_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='adventures.Adventure', verbose_name='adventure'),
        ),
        migrations.AlterField(
            model_name='story',
            name='next_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.Story', verbose_name='next story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='adventures.Resolution', verbose_name='resolution'),
        ),
        migrations.AlterField(
            model_name='story',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='adventures.Situation', verbose_name='situation'),
        ),
    ]
