# Generated by Django 2.2.12 on 2020-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0010_auto_20200502_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='difficulty',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='1-8 is easy, 10-12 is average, 14+ is difficult.', verbose_name='difficulty'),
            preserve_default=False,
        ),
    ]
