# Generated by Django 2.2.12 on 2020-05-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0011_adventure_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='antagonist_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adventures.AntagonistGoal', verbose_name='antagonist goal'),
        ),
    ]
