# Generated by Django 2.2.12 on 2020-05-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0012_resolution_antagonist_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='antagonistgoal',
            name='subject',
            field=models.CharField(default='', max_length=50, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
