# Generated by Django 2.2.12 on 2020-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0013_antagonistgoal_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antagonistgoal',
            name='level',
        ),
        migrations.AddField(
            model_name='resolution',
            name='level',
            field=models.IntegerField(default=0, verbose_name='level'),
            preserve_default=False,
        ),
    ]
