# Generated by Django 2.2.12 on 2020-05-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0014_auto_20200503_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='level',
        ),
        migrations.AddField(
            model_name='resolution',
            name='story_points',
            field=models.IntegerField(default=0, verbose_name='story points'),
            preserve_default=False,
        ),
    ]
