# Generated by Django 2.2.12 on 2020-05-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0018_auto_20200504_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antagonistgoal',
            name='adventure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antagonist_goals', to='adventures.Adventure', verbose_name='adventure'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='antagonist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antagonist_goals', to='adventures.Antagonist', verbose_name='antagonist'),
        ),
    ]
