# Generated by Django 2.2.13 on 2020-08-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0022_auto_20200830_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='', max_length=1, verbose_name='icon style'),
        ),
        migrations.AlterField(
            model_name='antagonist',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='', max_length=1, verbose_name='icon style'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='', max_length=1, verbose_name='icon style'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='', max_length=1, verbose_name='icon style'),
        ),
    ]
