# Generated by Django 2.2.13 on 2020-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0024_auto_20200830_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonist',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonist',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonist',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='antagonistgoal',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
