# Generated by Django 2.2.28 on 2025-08-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='source_url')),
                ('file_path', models.CharField(blank=True, max_length=1000, null=True, verbose_name='file path')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'chat message', 'verbose_name_plural': 'chat messages'},
        ),
    ]
