# Generated by Django 2.2.28 on 2025-08-31 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geminigm', '0003_chatmessage_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='author_it',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='ingesteddocument',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='ingesteddocument',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
