# Generated by Django 2.2.28 on 2025-08-31 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0004_auto_20250831_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='author_en',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='author_it',
        ),
    ]
