# Generated by Django 2.2.28 on 2025-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0006_auto_20250831_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingesteddocument',
            name='gemini_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
