# Generated by Django 2.2.28 on 2025-09-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0007_ingesteddocument_gemini_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingesteddocument',
            name='gemini_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID file Gemini'),
        ),
        migrations.AlterField(
            model_name='ingesteddocument',
            name='ingested_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ingestion date'),
        ),
        migrations.AlterField(
            model_name='ingesteddocument',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='source url'),
        ),
    ]
