# Generated by Django 2.2.28 on 2025-09-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0008_auto_20250906_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemmaIstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istruction', models.TextField(verbose_name='istruction')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ingestion date')),
            ],
            options={
                'verbose_name': 'Gemma istruction',
                'verbose_name_plural': 'Gemma istructions',
            },
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_response', models.TextField(verbose_name='bot response')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'Welcome message',
                'verbose_name_plural': 'Welcome messages',
            },
        ),
        migrations.AlterModelOptions(
            name='ingesteddocument',
            options={'verbose_name': 'ingested document', 'verbose_name_plural': 'ingested documents'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_response',
            field=models.TextField(verbose_name='bot response'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(verbose_name='user message'),
        ),
    ]
