# Generated by Django 2.2.28 on 2025-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0009_auto_20250907_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='istruction_en',
            field=models.TextField(null=True, verbose_name='istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='istruction_it',
            field=models.TextField(null=True, verbose_name='istruction'),
        ),
    ]
