# Generated by Django 2.2.28 on 2025-09-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0010_auto_20250907_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='istruction',
        ),
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='istruction_en',
        ),
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='istruction_it',
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
