# Generated by Django 2.2.28 on 2025-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0011_auto_20250907_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='description',
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='character_sheet_istruction',
            field=models.TextField(default='', verbose_name='charcater sheet istruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_en',
            field=models.TextField(null=True, verbose_name='charcater sheet istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_it',
            field=models.TextField(null=True, verbose_name='charcater sheet istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='summary_istruction',
            field=models.TextField(default='', verbose_name='summary istruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='summary_istruction_en',
            field=models.TextField(null=True, verbose_name='summary istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='summary_istruction_it',
            field=models.TextField(null=True, verbose_name='summary istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='system_instruction',
            field=models.TextField(default='', verbose_name='system istruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='system_instruction_en',
            field=models.TextField(null=True, verbose_name='system istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='system_instruction_it',
            field=models.TextField(null=True, verbose_name='system istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
