# Generated by Django 2.2.28 on 2025-09-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0012_auto_20250910_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='welcome_message_istruction',
            field=models.TextField(default='', verbose_name='welcome message istruction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='welcome_message_istruction_en',
            field=models.TextField(null=True, verbose_name='welcome message istruction'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='welcome_message_istruction_it',
            field=models.TextField(null=True, verbose_name='welcome message istruction'),
        ),
    ]
