# Generated by Django 2.2.28 on 2025-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0013_auto_20250910_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemmaistruction',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction',
            field=models.TextField(verbose_name='character sheet istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_en',
            field=models.TextField(null=True, verbose_name='character sheet istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_it',
            field=models.TextField(null=True, verbose_name='character sheet istruction'),
        ),
    ]
