# Generated by Django 2.2.28 on 2025-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0014_auto_20250910_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='bot_response_en',
            field=models.TextField(null=True, verbose_name='bot response'),
        ),
        migrations.AddField(
            model_name='welcomemessage',
            name='bot_response_it',
            field=models.TextField(null=True, verbose_name='bot response'),
        ),
    ]
