# Generated by Django 2.2.28 on 2025-09-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_auto_20240227_1455'),
        ('geminigm', '0015_auto_20250915_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='gemma_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemma', to='products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
