# Generated by Django 2.2.28 on 2025-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0016_auto_20250919_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='playtest_material',
            field=models.BooleanField(default=False, verbose_name='playtest material'),
        ),
    ]
