# Generated by Django 2.2.28 on 2025-09-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0017_gemmaistruction_playtest_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='playtest_material',
        ),
    ]
