# Generated by Django 2.2.28 on 2025-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0018_remove_gemmaistruction_playtest_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='short_description',
            field=models.TextField(blank=True, max_length=15, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='gemmaistruction',
            name='short_description_it',
            field=models.TextField(blank=True, max_length=15, null=True, verbose_name='short description'),
        ),
    ]
