# Generated by Django 2.2.28 on 2025-09-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0019_auto_20250922_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemmaistruction',
            name='short_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='short_description_it',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
    ]
