# Generated by Django 2.2.28 on 2025-09-24 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0020_auto_20250922_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='gemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='geminigm.GemmaIstruction', verbose_name='gemma'),
        ),
    ]
