# Generated by Django 2.2.28 on 2025-09-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0021_chatmessage_gemma'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomemessage',
            name='gemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_messages', to='geminigm.GemmaIstruction', verbose_name='gemma'),
        ),
    ]
