# Generated by Django 2.2.28 on 2026-08-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0022_welcomemessage_gemma'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_template', models.CharField(choices=[('geminigm/partials/_arcanum_builder.html', 'Arcanum Forge (Spell Calculator + AI)'), ('geminigm/partials/_astral_generator.html', 'd20 Astral Companion Generator'), ('geminigm/partials/_diventigm.html', 'Diventi AI GM')], default='geminigm/partials/_diventigm.html', help_text='Path to the partial template file to be included dynamically.', max_length=255, verbose_name='addon template path')),
                ('enable_ai', models.BooleanField(default=True, verbose_name='enable AI features')),
            ],
            options={
                'verbose_name': 'section addon',
                'verbose_name_plural': 'section addons',
            },
        ),
    ]
