# Generated by Django 2.2.28 on 2026-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0023_sectionaddon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaddon',
            name='title',
            field=models.CharField(default='GeminiGM', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
