# Generated by Django 2.2.28 on 2026-08-30 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0024_sectionaddon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemmaistruction',
            name='gemma_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemma', to='geminigm.SectionAddon', verbose_name='product'),
        ),
    ]
