# Generated by Django 2.2.28 on 2026-08-30 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0025_gemmaistruction_gemma_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction',
            field=models.TextField(blank=True, verbose_name='character sheet istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_en',
            field=models.TextField(blank=True, null=True, verbose_name='character sheet istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='character_sheet_istruction_it',
            field=models.TextField(blank=True, null=True, verbose_name='character sheet istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='gemma_section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemma', to='geminigm.SectionAddon', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='summary_istruction',
            field=models.TextField(blank=True, verbose_name='summary istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='summary_istruction_en',
            field=models.TextField(blank=True, null=True, verbose_name='summary istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='summary_istruction_it',
            field=models.TextField(blank=True, null=True, verbose_name='summary istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='welcome_message_istruction',
            field=models.TextField(blank=True, verbose_name='welcome message istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='welcome_message_istruction_en',
            field=models.TextField(blank=True, null=True, verbose_name='welcome message istruction'),
        ),
        migrations.AlterField(
            model_name='gemmaistruction',
            name='welcome_message_istruction_it',
            field=models.TextField(blank=True, null=True, verbose_name='welcome message istruction'),
        ),
    ]
