# Generated by Django 2.2.28 on 2026-08-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0026_auto_20260830_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionaddon',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
