# Generated by Django 2.2.28 on 2026-08-30 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geminigm', '0027_sectionaddon_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gemmaistruction',
            name='gemma_section',
        ),
        migrations.AddField(
            model_name='sectionaddon',
            name='gemma',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectionaddon', to='geminigm.GemmaIstruction', verbose_name='gemma istruction'),
        ),
    ]
