# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='profilepic/'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diventiuser', to='accounts.DiventiAvatar'),
        ),
    ]
