# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171029_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiavatar',
            name='image',
            field=models.ImageField(blank=True, upload_to='accounts/avatars/'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='accounts/profilepics/'),
        ),
    ]
