# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170924_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventiuser',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
