# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achievements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameField(
            model_name='achievement',
            old_name='user',
            new_name='users',
        ),
    ]
