# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_diventiuser_landing_page_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='landing_page_visibility',
            field=models.BooleanField(default=False),
        ),
    ]
