# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171226_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiavatar',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='diventiavatar',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='diventicover',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='diventicover',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='diventiavatar',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='diventiavatar',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='diventiavatar',
            name='staff_only',
            field=models.BooleanField(default=False, verbose_name='staff_only'),
        ),
        migrations.AlterField(
            model_name='diventicover',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='diventicover',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diventiuser', to='accounts.DiventiAvatar', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DiventiCover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='accounts/profilepics/', verbose_name='profilepic'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='role',
            field=models.CharField(blank=True, max_length=70, verbose_name='role'),
        ),
    ]
