# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171104_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diventiuser',
            old_name='landing_page_visibility',
            new_name='member',
        ),
    ]
