# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180226_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='modified',
        ),
    ]
