# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171104_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diventiuser', to='accounts.DiventiAvatar'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='member',
            field=models.BooleanField(default=False, help_text='If flagged the user will appear in the landing page.'),
        ),
    ]
