# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180226_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='users',
        ),
        migrations.AddField(
            model_name='diventiuser',
            name='achievements',
            field=models.ManyToManyField(related_name='users', to='accounts.Achievement'),
        ),
    ]
