# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20171112_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiavatar',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='diventiavatar',
            name='staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
