# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171112_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diventiuser',
            name='member',
        ),
    ]
