# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180226_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
