# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180226_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='language',
            field=models.CharField(choices=[('it', 'Italian'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
