# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_buyers'),
        ('accounts', '0007_remove_diventiuser_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='collection',
            field=models.ManyToManyField(related_name='collection', to='products.Product'),
        ),
    ]
