# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_diventiuser_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diventiuser',
            name='collection',
        ),
    ]
