# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_diventiuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='language',
            field=models.CharField(blank=True, choices=[('it', 'Italian'), ('en', 'English')], default='en', max_length=10, verbose_name='language'),
        ),
    ]
