# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180520_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.BooleanField(default=None, max_length=10, verbose_name='has agreed gdpr'),
        ),
    ]
