# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180520_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.BooleanField(verbose_name='has agreed to gdpr'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='language',
            field=models.CharField(blank=True, choices=[('it', 'Italian'), ('en', 'English')], default='en', max_length=2, verbose_name='language'),
        ),
    ]
