# Generated by Django 2.0.10 on 2019-02-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190209_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='role',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='role',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='role',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
