# Generated by Django 2.0.10 on 2019-03-01 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190209_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiventiProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label')),
                ('label_it', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
                ('label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
            ],
            options={
                'verbose_name': 'Profile picture',
                'verbose_name_plural': 'Profile pictures',
            },
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='profilepic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.DiventiProfilePic', verbose_name='profilepic'),
        ),
    ]
