# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180524_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.BooleanField(default=False, verbose_name='has agreed to gdpr'),
        ),
    ]
