# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180524_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='username',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
