# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180525_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.NullBooleanField(verbose_name='has agreed to gdpr'),
        ),
    ]
