# Generated by Django 2.0.5 on 2018-08-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180528_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='has_agreed_gdpr',
            field=models.NullBooleanField(verbose_name='subscriber status'),
        ),
    ]
