# Generated by Django 2.0.5 on 2018-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180805_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='diventiuser',
            name='bio_it',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
    ]
