# Generated by Django 2.1.7 on 2019-04-11 06:06

import diventi.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20190411_0806'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diventiuser',
            managers=[
                ('objects', diventi.accounts.models.DiventiUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='diventiavatar',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='diventicover',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='diventiprofilepic',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
    ]
