# Generated by Django 2.1.7 on 2019-05-12 14:01

import diventi.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0133_auto_20190512_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diventiuser',
            managers=[
                ('objects', diventi.accounts.models.DiventiUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='diventiuser',
            name='nametag',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='nametag'),
        ),
    ]
