# Generated by Django 2.1.7 on 2019-05-12 14:12

import diventi.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_auto_20190512_1609'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diventiuser',
            managers=[
                ('objects', diventi.accounts.models.DiventiUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='diventiuser',
            name='nametag',
            field=models.SlugField(max_length=200, unique=True, verbose_name='nametag'),
        ),
    ]
