# Generated by Django 2.2.1 on 2019-05-21 05:31

import diventi.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0150_auto_20190518_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventiuser',
            options={'ordering': ('nametag',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='diventiuser',
            managers=[
                ('objects', diventi.accounts.models.DiventiUserManager()),
            ],
        ),
    ]
