# Generated by Django 2.2.13 on 2020-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0334_auto_20200612_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='role',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
    ]
