# Generated by Django 2.2.24 on 2021-08-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0340_auto_20200901_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='language',
            field=models.CharField(choices=[('it', 'Italian'), ('en', 'English')], max_length=10, verbose_name='language'),
        ),
    ]
