# Generated by Django 2.2.28 on 2024-01-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0344_auto_20240102_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AddField(
            model_name='role',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
    ]
