# Generated by Django 2.2.28 on 2024-02-12 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0345_auto_20240127_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Deed', 'verbose_name_plural': 'Deeds'},
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('notified', models.BooleanField(default=False, verbose_name='notified')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Achievement', verbose_name='deed')),
                ('awarded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='awarded user')),
            ],
            options={
                'verbose_name': 'Award',
                'verbose_name_plural': 'Awards',
            },
        ),
        migrations.AddField(
            model_name='diventiuser',
            name='deeds',
            field=models.ManyToManyField(blank=True, through='accounts.Award', to='accounts.Achievement', verbose_name='deeds'),
        ),
    ]
