# Generated by Django 2.2.28 on 2024-02-12 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0346_auto_20240212_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='achievement',
            new_name='deed',
        ),
    ]
