# Generated by Django 2.2.28 on 2024-02-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0347_auto_20240212_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diventiuser',
            name='achievements',
        ),
    ]
