# Generated by Django 2.2.28 on 2025-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0348_remove_diventiuser_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='diventiuser',
            name='is_playtester',
            field=models.NullBooleanField(verbose_name='playtester status'),
        ),
    ]
