# Generated by Django 2.2.28 on 2025-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0349_diventiuser_is_playtester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventiuser',
            name='is_playtester',
            field=models.BooleanField(default=False, verbose_name='playtester status'),
        ),
    ]
