# Generated by Django 2.2.28 on 2025-09-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0350_auto_20250910_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventiuser',
            options={'ordering': ('nametag',), 'permissions': (('can_playtest', 'Can access playtest material'),), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='diventiuser',
            name='is_playtester',
        ),
    ]
