# Generated by Django 2.2.28 on 2026-01-05 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0351_auto_20250910_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
