# Generated by Django 2.0.8 on 2018-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0002_auto_20180817_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='section_type',
            field=models.CharField(blank=True, choices=[('commentbox', 'commentbox')], max_length=30),
        ),
    ]
