# Generated by Django 2.0.8 on 2018-08-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0003_brew_section_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('title_it', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('description', models.TextField(max_length=250, verbose_name='description')),
                ('description_it', models.TextField(max_length=250, null=True, verbose_name='description')),
                ('description_en', models.TextField(max_length=250, null=True, verbose_name='description')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('slug_it', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('title_it', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('content_it', models.TextField(null=True, verbose_name='content')),
                ('content_en', models.TextField(null=True, verbose_name='content')),
                ('section_type', models.CharField(blank=True, choices=[('commentbox', 'commentbox'), ('quotebox', 'quotebox')], max_length=30)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homebrew.Paper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Brew',
        ),
    ]
