# Generated by Django 2.0.8 on 2018-08-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0004_auto_20180819_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
