# Generated by Django 2.0.8 on 2018-08-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0005_section_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order_id',
        ),
        migrations.AddField(
            model_name='section',
            name='section_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
