# Generated by Django 2.0.8 on 2018-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0006_auto_20180819_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
        migrations.AddField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order_id',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
