# Generated by Django 2.0.8 on 2018-08-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0007_auto_20180819_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='order_id'),
        ),
        migrations.AlterField(
            model_name='section',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='homebrew.Paper'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('commentbox', 'commentbox'), ('quotebox', 'quotebox')], max_length=30, verbose_name='section_type'),
        ),
    ]
