# Generated by Django 2.0.8 on 2018-08-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0010_auto_20180819_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox')], max_length=30, verbose_name='section type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='theme',
            field=models.CharField(blank=True, choices=[('PhbLightGreen', 'PhbLightGreen'), ('PhbLightCyan', 'PhbLightCyan'), ('PhbMauve', 'PhbMauve'), ('PhbTan', 'PhbTan'), ('DmgLavender', 'DmgLavender'), ('DmgCoral', 'DmgCoral'), ('DmgSlateGray', 'DmgSlateGray'), ('DmgLilac', 'DmgLilac')], max_length=30, verbose_name='theme'),
        ),
    ]
