# Generated by Django 2.0.8 on 2018-08-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0011_auto_20180819_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice', models.CharField(choices=[(20, 'd20'), (12, 'd12'), (10, 'd10'), (8, 'd8'), (6, 'd6'), (4, 'd4')], max_length=3, verbose_name='dice')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='DiceTableRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('dicetable', 'dicetable')], max_length=30, verbose_name='section type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='theme',
            field=models.CharField(blank=True, choices=[('PhbLightGreen', 'light green'), ('PhbLightCyan', 'light chan'), ('PhbMauve', 'muave'), ('PhbTan', 'tan'), ('DmgLavender', 'lavender'), ('DmgCoral', 'coral'), ('DmgSlateGray', 'slate gray'), ('DmgLilac', 'lilac')], max_length=30, verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='section',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.DiceTable'),
        ),
    ]
