# Generated by Django 2.0.8 on 2018-08-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0012_auto_20180819_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='table',
        ),
    ]
