# Generated by Django 2.0.8 on 2018-08-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0013_remove_section_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicetable',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dicetable',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='dicetablerow',
            name='description_en',
            field=models.CharField(max_length=60, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='dicetablerow',
            name='description_it',
            field=models.CharField(max_length=60, null=True, verbose_name='description'),
        ),
    ]
