# Generated by Django 2.0.8 on 2018-08-19 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0014_auto_20180819_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicetablerow',
            name='dicetable',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='homebrew.DiceTable'),
            preserve_default=False,
        ),
    ]
