# Generated by Django 2.0.8 on 2018-08-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0018_remove_section_dicetable2'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.DiceTable'),
        ),
    ]
