# Generated by Django 2.0.8 on 2018-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0020_auto_20180824_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='titlepage',
            field=models.CharField(choices=[('diventi_pc', 'diventi_pc')], default='', max_length=60, verbose_name='titlepage'),
            preserve_default=False,
        ),
    ]
