# Generated by Django 2.0.8 on 2018-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0021_paper_titlepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='titlepage',
            field=models.CharField(blank=True, choices=[('diventi_pc', 'diventi_pc')], max_length=60, verbose_name='titlepage'),
        ),
    ]
