# Generated by Django 2.0.8 on 2018-08-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0022_auto_20180825_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='titlepage',
        ),
    ]
