# Generated by Django 2.0.8 on 2018-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0024_auto_20180825_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title_page',
            field=models.BooleanField(default=False, verbose_name='title page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('dicetable', 'dicetable')], max_length=30, verbose_name='section type'),
        ),
    ]
