# Generated by Django 2.0.8 on 2018-08-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0025_auto_20180825_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicetablerow',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dicetablerow',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dicetablerow',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
