# Generated by Django 2.0.8 on 2018-08-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0027_dicetablerow_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itemize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='ItemizeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='description')),
                ('itemize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='homebrew.Itemize')),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('paragraph', 'paragraph'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('dicetable', 'dicetable')], max_length=30, verbose_name='section type'),
        ),
    ]
