# Generated by Django 2.0.8 on 2018-08-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0028_auto_20180825_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemize',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemize',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='itemizeitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='itemizeitem',
            name='description_it',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
