# Generated by Django 2.0.8 on 2018-08-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0030_section__list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.Itemize', verbose_name='list'),
        ),
        migrations.AlterField(
            model_name='section',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.DiceTable', verbose_name='talbe'),
        ),
    ]
