# Generated by Django 2.0.8 on 2018-08-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0031_auto_20180825_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.DiceTable', verbose_name='table'),
        ),
    ]
