# Generated by Django 2.0.8 on 2018-08-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0034_auto_20180826_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('subsubsection', 'subsubsection'), ('paragraph', 'paragraph'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('header', 'header'), ('phantom', 'phantom')], max_length=30, verbose_name='section type'),
        ),
    ]
