# Generated by Django 2.0.8 on 2018-08-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0036_auto_20180826_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
    ]
