# Generated by Django 2.0.8 on 2018-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0037_auto_20180826_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('subsubsection', 'subsubsection'), ('paragraph', 'paragraph'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('header', 'header'), ('phantom', 'phantom'), ('picture', 'picture')], max_length=30, verbose_name='section type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='theme',
            field=models.CharField(blank=True, choices=[('PhbLightCyan', 'green'), ('PhbTan', 'yellow'), ('DmgCoral', 'orange'), ('DmgSlateGray', 'gray')], max_length=30, verbose_name='theme'),
        ),
    ]
