# Generated by Django 2.0.8 on 2018-08-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0039_section_illustration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='illustration',
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('subsubsection', 'subsubsection'), ('paragraph', 'paragraph'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('header', 'header'), ('phantom', 'phantom'), ('illustration', 'illustration')], max_length=30, verbose_name='section type'),
        ),
    ]
