# Generated by Django 2.0.8 on 2018-08-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0041_section__illustration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_illustration',
            field=models.CharField(blank=True, choices=[('parassite', 'parassite'), ('parassite_lineart', 'parassite (lineart)')], max_length=30, verbose_name='illustration'),
        ),
    ]
