# Generated by Django 2.0.8 on 2018-08-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0042_auto_20180830_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_illustration',
            field=models.CharField(blank=True, choices=[('parassite', 'parassite'), ('parassite_lineart', 'parassite (lineart)'), ('dama_electra', 'dama electra'), ('dama_electra_lineart', 'dama electra (lineart)'), ('xarieth', 'xarieth'), ('xarieth_lineart', 'xarieth (lineart)'), ('tiara', 'tiara'), ('tiara_lineart', 'tiara (lineart)')], max_length=30, verbose_name='illustration'),
        ),
    ]
