# Generated by Django 2.0.8 on 2018-09-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0043_auto_20180830_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterblock',
            options={'verbose_name': 'character block', 'verbose_name_plural': 'character blocks'},
        ),
        migrations.AlterModelOptions(
            name='characteritem',
            options={'verbose_name': 'character item', 'verbose_name_plural': 'character items'},
        ),
        migrations.AlterModelOptions(
            name='dicetable',
            options={'verbose_name': 'dice table', 'verbose_name_plural': 'dice tables'},
        ),
        migrations.AlterModelOptions(
            name='dicetablerow',
            options={'verbose_name': 'dice table row', 'verbose_name_plural': 'dice table rows'},
        ),
        migrations.AlterModelOptions(
            name='itemize',
            options={'verbose_name': 'list', 'verbose_name_plural': 'lists'},
        ),
        migrations.AlterModelOptions(
            name='itemizeitem',
            options={'verbose_name': 'list item', 'verbose_name_plural': 'list items'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name': 'paper', 'verbose_name_plural': 'papers'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
        migrations.AlterModelOptions(
            name='watermark',
            options={'verbose_name': 'watermark', 'verbose_name_plural': 'watermarks'},
        ),
    ]
