# Generated by Django 2.0.8 on 2018-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0044_auto_20180902_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='template',
            field=models.CharField(choices=[('diventi_a4', 'diventi_a4'), ('diventi_a5', 'diventi_a5')], default='diventi_a4', max_length=60, verbose_name='template'),
            preserve_default=False,
        ),
    ]
