# Generated by Django 2.0.8 on 2018-09-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0045_paper_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='template',
            field=models.CharField(choices=[('diventi_book_a4.tex', 'libro diventi - formato A4'), ('diventi_book_a5.tex', 'libro diventi - formato A5')], max_length=60, verbose_name='template'),
        ),
    ]
