# Generated by Django 2.0.8 on 2018-09-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0046_auto_20180922_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.Itemize', verbose_name='list'),
        ),
        migrations.AlterField(
            model_name='section',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.CharacterBlock', verbose_name='character'),
        ),
        migrations.AlterField(
            model_name='section',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section', to='homebrew.DiceTable', verbose_name='table'),
        ),
    ]
