# Generated by Django 2.0.8 on 2018-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0047_auto_20180922_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order_id',
            field=models.PositiveIntegerField(verbose_name='order_id'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('id', 'order_id')},
        ),
    ]
