# Generated by Django 2.0.8 on 2018-10-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0048_auto_20180923_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'card',
                'verbose_name_plural': 'cards',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(blank=True, choices=[('section', 'section'), ('subsection', 'subsection'), ('subsubsection', 'subsubsection'), ('paragraph', 'paragraph'), ('commentbox', 'commentbox'), ('quotebox', 'quotebox'), ('paperbox', 'paperbox'), ('header', 'header'), ('phantom', 'phantom'), ('illustration', 'illustration'), ('card', 'card')], max_length=30, verbose_name='section type'),
        ),
    ]
