# Generated by Django 2.0.8 on 2018-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0049_auto_20181004_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='template',
            field=models.CharField(choices=[('diventi_book_a4.tex', 'diventi book - A4'), ('diventi_book_a5.tex', 'diventi book - A5'), ('diventi_card_a4.tex', 'diventi card - A4')], max_length=60, verbose_name='template'),
        ),
    ]
