# Generated by Django 2.0.8 on 2018-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0055_section_diventicard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='card',
            name='flavortext',
            field=models.TextField(blank=True, verbose_name='flavortext'),
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='title'),
            preserve_default=False,
        ),
    ]
