# Generated by Django 2.0.8 on 2018-10-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebrew', '0058_section__card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='_illustration',
            field=models.CharField(blank=True, choices=[('placeholder', 'placeholder'), ('parassite', 'parassite'), ('parassite_lineart', 'parassite (lineart)'), ('dama_electra', 'dama electra'), ('dama_electra_lineart', 'dama electra (lineart)'), ('xarieth', 'xarieth'), ('xarieth_lineart', 'xarieth (lineart)'), ('tiara', 'tiara'), ('tiara_lineart', 'tiara (lineart)'), ('armeria', 'armory'), ('cristallo1', 'crystal1'), ('cristallo2', 'crystal2'), ('cristallo3', 'crystal3'), ('diventi_logo_bianco', 'diventi logo (white)'), ('entrata', 'entrance'), ('nucleo', 'core'), ('portale', 'portal'), ('silos', 'silos'), ('trono', 'throne')], max_length=30, verbose_name='illustration'),
        ),
    ]
