# Generated by Django 2.2.28 on 2022-10-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='courtesy_message',
            field=models.TextField(default='Pacchetto parzialmente acquistato', help_text='Folded products return this message to all users', verbose_name='courtesy message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='courtesy_short_message',
            field=models.CharField(default='Alcuni oggetti di questo pacchetto risultano già acquistati, non è possibile procedere.', max_length=50, verbose_name='short courtesy messages'),
            preserve_default=False,
        ),
    ]
