# Generated by Django 2.2.28 on 2022-10-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20221018_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='short_description',
            field=models.TextField(blank=True, max_length=50, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='package',
            name='short_description_it',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='short description'),
        ),
    ]
