# Generated by Django 2.2.28 on 2022-10-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='faq',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
