# Generated by Django 2.2.28 on 2022-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20221021_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='description_it',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_it',
            field=models.TextField(null=True, verbose_name='answer'),
        ),
    ]
