# Generated by Django 2.2.28 on 2022-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_auto_20221021_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='abstract',
            field=models.TextField(blank=True, max_length=200, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='package',
            name='abstract_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='package',
            name='abstract_it',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='abstract'),
        ),
    ]
