# Generated by Django 2.2.28 on 2022-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20221021_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='slug_it',
        ),
    ]
