# Generated by Django 2.2.28 on 2023-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20221022_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='hot',
            field=models.BooleanField(default=False, help_text='Hot objects are displayed on the featured section of landing page', verbose_name='hot'),
        ),
    ]
