# Generated by Django 2.2.28 on 2023-03-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0011_package_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hot',
        ),
        migrations.AddField(
            model_name='package',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured objects are displayed on the top of their page. If pinned, they are also displayed on the top of the landing page', verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='package',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned objects appear on the navbar and on the landing page', verbose_name='pinned'),
        ),
    ]
