# Generated by Django 2.2.28 on 2026-01-05 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0016_auto_20240127_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
    ]
