# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0017_auto_20260105_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='package',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
    ]
