# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_diventicomment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventicomment',
            options={},
        ),
        migrations.AddField(
            model_name='diventicomment',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diventicomment',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diventicomment',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diventicomment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
