# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180101_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventicomment',
            options={'ordering': ('submit_date',), 'permissions': [('can_moderate', 'Can moderate comments')], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='diventicomment',
            name='level',
        ),
        migrations.RemoveField(
            model_name='diventicomment',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='diventicomment',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='diventicomment',
            name='tree_id',
        ),
    ]
