# Generated by Django 2.0.5 on 2018-05-28 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180528_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventicomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diventicomment_comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
