# Generated by Django 2.2.13 on 2020-07-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20180528_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventicomment',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='diventicomment',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='diventicomment',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
