# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_diventicomment_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diventicomment',
            name='points',
        ),
    ]
