# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20180105_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diventicomment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
