# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 10:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20180106_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diventicomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.DiventiComment', verbose_name='parent'),
        ),
    ]
