# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20180106_1551'),
        ('comments', '0010_auto_20180107_1135'),
    ]

    operations = [
    ]
