# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 09:40
from __future__ import unicode_literals

import diventi.products.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180226_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=diventi.products.fields.ProtectedFileField(blank=True, upload_to='products/files/', verbose_name='file'),
        ),
    ]
