# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171225_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='color',
            field=models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='color',
            field=models.CharField(choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='icon',
            field=models.CharField(max_length=30, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='image',
            field=models.URLField(verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
