# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_imagepreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepreview',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
