# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20180304_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.ChapterCategory', verbose_name='category'),
            preserve_default=False,
        ),
    ]
