# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180319_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductCategory', verbose_name='category'),
        ),
    ]
