# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171120_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreview',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagepreviews', to='products.Product'),
            preserve_default=False,
        ),
    ]
