# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180106_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepreview',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
    ]
