# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-14 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180106_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={'verbose_name': 'Characteristic', 'verbose_name_plural': 'Characteristics'},
        ),
    ]
