# Generated by Django 2.0.5 on 2018-05-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180513_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ChapterCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characteristics', to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagepreviews', to='products.Product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductCategory', verbose_name='category'),
        ),
    ]
