# Generated by Django 2.0.5 on 2018-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courtesy_message',
            field=models.TextField(blank=True, verbose_name='courtesy message'),
        ),
    ]
