# Generated by Django 2.0.5 on 2018-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_courtesy_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courtesy_message_en',
            field=models.TextField(blank=True, null=True, verbose_name='courtesy message'),
        ),
        migrations.AddField(
            model_name='product',
            name='courtesy_message_it',
            field=models.TextField(blank=True, null=True, verbose_name='courtesy message'),
        ),
    ]
