# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0012_product_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(related_name='collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
