# Generated by Django 2.0.8 on 2019-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180902_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='abstract',
            field=models.TextField(blank=True, max_length=200, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='product',
            name='abstract_en',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='abstract'),
        ),
        migrations.AddField(
            model_name='product',
            name='abstract_it',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='abstract'),
        ),
    ]
