# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-21 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20180121_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_it',
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_it',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
