# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_buyers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyers',
        ),
    ]
