# Generated by Django 2.1.7 on 2019-04-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20190411_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='product',
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
