# Generated by Django 2.1.7 on 2019-04-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
