# Generated by Django 2.2.1 on 2019-06-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190524_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courtesy_short_message',
            field=models.CharField(blank=True, max_length=50, verbose_name='short courtesy messages'),
        ),
        migrations.AddField(
            model_name='product',
            name='courtesy_short_message_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short courtesy messages'),
        ),
        migrations.AddField(
            model_name='product',
            name='courtesy_short_message_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='short courtesy messages'),
        ),
    ]
