# Generated by Django 2.2.4 on 2019-08-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190607_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(related_name='_product_related_products_+', to='products.Product', verbose_name='related products'),
        ),
    ]
