# Generated by Django 2.2.10 on 2020-02-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200119_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='meta_category',
            field=models.BooleanField(default=False, verbose_name='meta category'),
        ),
    ]
