# Generated by Django 2.2.10 on 2020-02-25 21:05

from django.db import migrations

def create_customers(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Product = apps.get_model('products', 'Product')
    for product in Product.objects.all():
        buyers = product.buyers.all()
        customers = product.customers.set(buyers)
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20200225_0743'),
    ]

    operations = [
        migrations.RunPython(create_customers),
    ]
