# Generated by Django 2.2.10 on 2020-02-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_buyers_to_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
