# Generated by Django 2.2.10 on 2020-03-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20200301_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
