# Generated by Django 2.2.10 on 2020-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_auto_20200301_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='meta_category',
            field=models.BooleanField(default=False, help_text="Meta categories won't be listed in search results.", verbose_name='meta category'),
        ),
    ]
