# Generated by Django 2.2.13 on 2020-08-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20200801_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='products.ProductCategory', verbose_name='category'),
        ),
    ]
