# Generated by Django 2.2.13 on 2020-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
