# Generated by Django 2.2.13 on 2020-08-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_productdetail_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='featured',
        ),
    ]
