# Generated by Django 2.2.13 on 2020-08-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_remove_productdetail_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='highlighted'),
        ),
    ]
