# Generated by Django 2.2.13 on 2020-08-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_productformat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productformat',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ProductFormat', verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.ProductCategory', verbose_name='category'),
        ),
    ]
