# Generated by Django 2.2.13 on 2020-08-21 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_auto_20200820_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='product',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='productformat',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='products.ProductCategory', verbose_name='category'),
        ),
    ]
