# Generated by Django 2.2.13 on 2020-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_auto_20200821_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepreview',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='imagepreview',
            name='label_it',
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='description_it',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='icon_style',
            field=models.CharField(choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='imagepreview',
            name='title_it',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.ProductFormat', verbose_name='formats'),
        ),
    ]
