# Generated by Django 2.2.13 on 2020-08-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_auto_20200826_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=50, verbose_name='stripe price'),
        ),
    ]
