# Generated by Django 2.2.13 on 2020-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0059_auto_20200830_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productformat',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productformat',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='productformat',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
