# Generated by Django 2.2.16 on 2021-03-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0063_product_product_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='pinned'),
        ),
    ]
