# Generated by Django 2.2.16 on 2021-03-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_auto_20210321_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='early_access',
            field=models.BooleanField(default=True, verbose_name='early_access'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinned',
            field=models.BooleanField(default=True, verbose_name='pinned'),
        ),
    ]
