# Generated by Django 2.2.18 on 2021-03-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_auto_20210321_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='early_access',
            field=models.BooleanField(default=True, verbose_name='early access'),
        ),
    ]
