# Generated by Django 2.2.24 on 2021-10-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_auto_20210322_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='early_access',
        ),
    ]
