# Generated by Django 2.2.24 on 2021-10-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0071_remove_product_early_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='order index'),
        ),
    ]
