# Generated by Django 2.2.24 on 2021-10-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_product_order_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_index',
        ),
    ]
