# Generated by Django 2.2.24 on 2022-01-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_remove_product_order_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug_it',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
