# Generated by Django 2.2.24 on 2022-01-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0074_auto_20220114_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='hot'),
        ),
    ]
