# Generated by Django 2.2.28 on 2022-09-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0076_productcover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='courtesy_message',
            field=models.TextField(blank=True, help_text='Folded products return this message to all users', verbose_name='courtesy message'),
        ),
        migrations.AlterField(
            model_name='product',
            name='courtesy_message_en',
            field=models.TextField(blank=True, help_text='Folded products return this message to all users', null=True, verbose_name='courtesy message'),
        ),
        migrations.AlterField(
            model_name='product',
            name='courtesy_message_it',
            field=models.TextField(blank=True, help_text='Folded products return this message to all users', null=True, verbose_name='courtesy message'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, help_text='Hot products are displayed on top of the games page', verbose_name='hot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pinned',
            field=models.BooleanField(default=True, help_text='Pinned products appear on the landing page', verbose_name='pinned'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public',
            field=models.BooleanField(default=False, help_text='Public products diplay their content to anonimous users', verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unfolded',
            field=models.BooleanField(default=False, help_text='Unfolded products can be bought by users', verbose_name='unfolded'),
        ),
    ]
