# Generated by Django 2.2.28 on 2022-10-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190430_1532'),
        ('products', '0077_auto_20220917_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('publishablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=80, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=30, verbose_name='icon')),
                ('icon_style', models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('color', models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='default', max_length=30, verbose_name='color')),
                ('pinned', models.BooleanField(default=True, help_text='Pinned packages appear on the landing page', verbose_name='pinned')),
                ('stripe_price', models.CharField(blank=True, max_length=50, verbose_name='stripe price')),
                ('stripe_product', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='stripe product')),
                ('related_products', models.ManyToManyField(blank=True, related_name='packages', to='products.Product', verbose_name='related products')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
            bases=('core.publishablemodel', models.Model),
        ),
    ]
