# Generated by Django 2.2.28 on 2022-10-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0080_auto_20221016_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
