# Generated by Django 2.2.28 on 2022-10-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0081_delete_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='postcard_image',
            field=models.URLField(blank=True, verbose_name='postcard_image'),
        ),
    ]
