# Generated by Django 2.2.28 on 2022-10-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0082_product_postcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='postcard_image',
        ),
        migrations.AddField(
            model_name='product',
            name='postcard',
            field=models.URLField(blank=True, verbose_name='postcard'),
        ),
    ]
