# Generated by Django 2.2.28 on 2022-10-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0083_auto_20221022_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, verbose_name='cover'),
        ),
    ]
