# Generated by Django 2.2.28 on 2022-10-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20211024_1100'),
        ('products', '0084_auto_20221022_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='products', to='blog.Article', verbose_name='related articles'),
        ),
    ]
