# Generated by Django 2.2.28 on 2023-02-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0085_product_related_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='relatable',
            field=models.BooleanField(default=False, help_text='Activate to show related objects', verbose_name='relatable'),
        ),
    ]
