# Generated by Django 2.2.28 on 2023-02-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0086_product_relatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='relatable',
            field=models.BooleanField(default=True, help_text='Activate to show related objects', verbose_name='relatable'),
        ),
    ]
