# Generated by Django 2.2.28 on 2023-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0087_auto_20230211_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hot',
            field=models.BooleanField(default=False, help_text='Hot objects are displayed on the featured section of landing page', verbose_name='hot'),
        ),
    ]
