# Generated by Django 2.2.28 on 2024-01-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0092_auto_20240102_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AddField(
            model_name='chaptercategory',
            name='title_plural',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
