# Generated by Django 2.2.28 on 2024-01-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0094_auto_20240127_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='title_plural_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='plural title'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_plural_it',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='plural title'),
        ),
    ]
