# Generated by Django 2.2.28 on 2024-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0096_remove_product_relatable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='col_lg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='col_md',
        ),
        migrations.RemoveField(
            model_name='product',
            name='col_sm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_lg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_md',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_sm',
        ),
    ]
