# Generated by Django 2.2.28 on 2024-02-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0097_auto_20240206_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='formats',
        ),
        migrations.AddField(
            model_name='product',
            name='formats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.ProductFormat', verbose_name='formats'),
        ),
    ]
