# Generated by Django 2.2.28 on 2024-02-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0012_auto_20200423_1049'),
        ('products', '0099_auto_20240206_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_forum_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_conversation.Topic'),
        ),
    ]
