# Generated by Django 2.2.28 on 2024-02-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0100_product_related_forum_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_forum_topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_conversation.Topic', verbose_name='related forum topic'),
        ),
    ]
