# Generated by Django 2.2.28 on 2024-02-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum_conversation', '0012_auto_20200423_1049'),
        ('products', '0101_auto_20240213_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_forum_topic_en',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_conversation.Topic', verbose_name='related forum topic'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_forum_topic_it',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forum_conversation.Topic', verbose_name='related forum topic'),
        ),
    ]
