# Generated by Django 2.2.28 on 2024-02-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0102_auto_20240213_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='file_it',
        ),
        migrations.AddField(
            model_name='product',
            name='image_en',
            field=models.URLField(blank=True, null=True, verbose_name='cover'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_it',
            field=models.URLField(blank=True, null=True, verbose_name='cover'),
        ),
    ]
