# Generated by Django 2.2.28 on 2024-02-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0103_auto_20240227_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_it',
        ),
    ]
