# Generated by Django 2.2.28 on 2025-09-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0104_auto_20240227_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='playtest_material',
            field=models.BooleanField(default=False, verbose_name='playtest material'),
        ),
    ]
