# Generated by Django 2.2.28 on 2025-09-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0105_product_playtest_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='playtest_material',
            field=models.BooleanField(default=False, help_text='Playtest products can be accessed by users with a playtest permission', verbose_name='playtest material'),
        ),
    ]
