# Generated by Django 2.2.28 on 2026-01-04 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0106_auto_20250922_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(blank=True, verbose_name='image')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label')),
            ],
            options={
                'verbose_name': 'section image',
                'verbose_name_plural': 'section images',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='postcard',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_primary', to='products.ProductImage', verbose_name='primary cover'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_secondary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_secondary', to='products.ProductImage', verbose_name='secondary cover'),
        ),
    ]
