# Generated by Django 2.2.28 on 2026-01-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0109_productdownloadsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdownloadsession',
            options={'verbose_name': 'Download session', 'verbose_name_plural': 'Download sessions'},
        ),
    ]
