# Generated by Django 2.2.28 on 2026-01-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0110_auto_20260106_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdownloadsession',
            name='stripe_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='stripe email'),
        ),
    ]
