# Generated by Django 2.2.28 on 2026-01-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0111_productdownloadsession_stripe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdownloadsession',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product', verbose_name='product'),
        ),
    ]
