# Generated by Django 2.2.28 on 2026-01-09 17:57

import diventi.core.storages
import diventi.products.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0112_productdownloadsession_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file_en',
            field=diventi.products.fields.ProtectedFileField(blank=True, null=True, storage=diventi.core.storages.MediaStorage(acl='private'), upload_to='products/files/', verbose_name='file'),
        ),
        migrations.AddField(
            model_name='product',
            name='file_it',
            field=diventi.products.fields.ProtectedFileField(blank=True, null=True, storage=diventi.core.storages.MediaStorage(acl='private'), upload_to='products/files/', verbose_name='file'),
        ),
    ]
