# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0114_auto_20260301_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='imagepreview',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_plural_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_plural_it',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productcover',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='productformat',
            name='title_plural',
            field=models.CharField(blank=True, max_length=80, verbose_name='plural title'),
        ),
    ]
