# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:27
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publishablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('title_it', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('title_en', models.CharField(max_length=60, null=True, verbose_name='title')),
                ('description', ckeditor.fields.RichTextField(max_length=250, verbose_name='description')),
                ('description_it', ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='description')),
                ('description_en', ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=60, verbose_name='caption')),
                ('caption_it', models.CharField(blank=True, max_length=60, null=True, verbose_name='caption')),
                ('caption_en', models.CharField(blank=True, max_length=60, null=True, verbose_name='caption')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('content_it', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='content')),
                ('hot', models.BooleanField(default=False, verbose_name='hot')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('slug_it', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('slug_en', models.SlugField(null=True, unique=True, verbose_name='slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'articles',
            },
            bases=('core.publishablemodel', models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('title_it', models.CharField(max_length=60, null=True, unique=True)),
                ('title_en', models.CharField(max_length=60, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='article',
            name='promotions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='promotions'),
        ),
    ]
