# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 16:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='promotions',
            field=models.ManyToManyField(blank=True, related_name='promotions', to=settings.AUTH_USER_MODEL),
        ),
    ]
