# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('title_it', models.CharField(max_length=60, null=True, unique=True)),
                ('title_en', models.CharField(max_length=60, null=True, unique=True)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label')),
            ],
            options={
                'verbose_name': 'Blog Cover',
                'verbose_name_plural': 'Blog Covers',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleCategory', verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
