# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='article',
            name='promotions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='promotions'),
        ),
    ]
