# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 10:13
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180105_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='article',
            name='caption_it',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_it',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_it',
            field=ckeditor.fields.RichTextField(max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='article',
            name='hot_en',
            field=models.BooleanField(default=False, verbose_name='hot'),
        ),
        migrations.AddField(
            model_name='article',
            name='hot_it',
            field=models.BooleanField(default=False, verbose_name='hot'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_it',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='caption',
            field=models.CharField(blank=True, max_length=60, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='hot'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=60, verbose_name='title'),
        ),
    ]
