# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/diventi/'),
        ),
        migrations.DeleteModel(
            name='HeaderImage',
        ),
    ]
