# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171117_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='abstract',
            new_name='description',
        ),
    ]
