# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180204_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcover',
            name='label_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='blogcover',
            name='label_it',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='label'),
        ),
    ]
