# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180106_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hot_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hot_it',
        ),
    ]
