# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180204_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcover',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
