# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171217_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='article',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
