# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 19:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171010_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
