# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcover_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_en',
            field=models.TextField(max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description_it',
            field=models.TextField(max_length=250, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogcover',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
