# Generated by Django 2.1.7 on 2019-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180526_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='blogcover',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
    ]
