# Generated by Django 2.2.10 on 2020-02-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190411_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcover',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Blue'), ('primary', 'Rose'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('default', 'Gray')], default='warning', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='blogcover',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='blogcover',
            name='icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='blogcover',
            name='title',
            field=models.CharField(default='our latest stories', max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
    ]
