# Generated by Django 2.2.16 on 2021-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201213_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='col_sm',
            field=models.PositiveIntegerField(choices=[(12, 'Wide'), (8, 'Three fourths'), (6, 'Half'), (4, 'Narrow')], default=12, verbose_name='sm column'),
        ),
    ]
