# Generated by Django 2.2.16 on 2021-03-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210321_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='col_lg',
            field=models.PositiveIntegerField(choices=[(12, 'Full (12)'), (8, 'Two thirds (8)'), (6, 'Half (6)'), (4, 'One third (4)'), (3, 'One fourth (3)')], default=12, verbose_name='lg column'),
        ),
        migrations.AlterField(
            model_name='article',
            name='col_md',
            field=models.PositiveIntegerField(choices=[(12, 'Full (12)'), (8, 'Two thirds (8)'), (6, 'Half (6)'), (4, 'One third (4)'), (3, 'One fourth (3)')], default=12, verbose_name='md column'),
        ),
        migrations.AlterField(
            model_name='article',
            name='col_sm',
            field=models.PositiveIntegerField(choices=[(12, 'Full (12)'), (8, 'Two thirds (8)'), (6, 'Half (6)'), (4, 'One third (4)'), (3, 'One fourth (3)')], default=12, verbose_name='sm column'),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='default', max_length=30, verbose_name='color'),
        ),
    ]
