# Generated by Django 2.2.24 on 2021-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210321_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='articlecategory',
            name='default',
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('dark', 'Black'), ('light', 'White')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='icon',
            field=models.CharField(blank=True, max_length=30, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('r', 'r - regular'), ('s', 's - solid'), ('l', 'l - light'), ('d', 'd - duotone'), ('b', 'b - brand')], default='r', max_length=1, verbose_name='icon style'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title_it',
            field=models.CharField(max_length=80, null=True, verbose_name='title'),
        ),
    ]
