# Generated by Django 2.2.24 on 2021-10-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20210919_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category', 'verbose_name_plural': 'Article Categories'},
        ),
    ]
