# Generated by Django 2.2.28 on 2022-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20211024_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='postcard',
            field=models.URLField(blank=True, verbose_name='postcard'),
        ),
    ]
