# Generated by Django 2.2.28 on 2024-01-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_article_postcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('gray', 'Light gray')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('gray', 'Light gray')], default='default', max_length=30, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='blogcover',
            name='color',
            field=models.CharField(blank=True, choices=[('info', 'Light blue'), ('primary', 'Blue'), ('danger', 'Red'), ('warning', 'Yellow'), ('success', 'Green'), ('secondary', 'Gray'), ('gray-dark', 'Black'), ('white', 'White'), ('indigo', 'Indigo'), ('purple', 'Purple'), ('pink', 'Pink'), ('yellow', 'Yellow'), ('cyan', 'Cyan'), ('gray', 'Light gray')], default='default', max_length=30, verbose_name='color'),
        ),
    ]
