# Generated by Django 2.2.28 on 2026-01-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20240127_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=False, help_text='Featured objects are displayed on the top of their page. If pinned, they are also displayed on the top of the landing page', verbose_name='featured'),
        ),
        migrations.AddField(
            model_name='article',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned objects appear on the navbar and on the landing page', verbose_name='pinned'),
        ),
    ]
