# Generated by Django 2.2.28 on 2026-01-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20260104_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hot',
        ),
    ]
