# Generated by Django 2.2.28 on 2026-03-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20260105_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title_plural_en',
            field=models.CharField(max_length=80, null=True, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='title_plural_it',
            field=models.CharField(max_length=80, null=True, verbose_name='plural title'),
        ),
        migrations.AlterField(
            model_name='blogcover',
            name='title_plural',
            field=models.CharField(max_length=80, verbose_name='plural title'),
        ),
    ]
