# Generated by Django 2.2.28 on 2026-03-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20260301_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='slug',
            field=models.SlugField(default='', verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_en',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='slug_it',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
