# Generated by Django 2.2.28 on 2026-04-19 09:31

from django.db import migrations, models
from django.utils.text import slugify


def migrate_slugs(apps, schema_editor):
    articlecategory = apps.get_model("blog", "articlecategory")
    instances = articlecategory.objects.all()
    for instance in instances:
        slug_it = slugify(instance.title_it)
        instance.slug_it=slug_it
        slug_en = slugify(instance.title_en)
        instance.slug_en=slug_en
        print('Aggiornato slug {} - {}'.format(instance.title, instance.slug_it))


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_auto_20260301_1150'),
    ]

    operations = [
        migrations.RunPython(migrate_slugs),
    ]
