# Generated by Django 2.2.2 on 2019-06-20 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebooks', '0062_auto_20190619_0817'),
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactersheet',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ebooks.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
