# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('publication_date', models.DateTimeField(blank=True, null=True, verbose_name='publication_date')),
            ],
        ),
    ]
