# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171223_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishablemodel',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publication_date'),
        ),
        migrations.AlterField(
            model_name='publishablemodel',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
