# Generated by Django 2.0.8 on 2018-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='content_it',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_it',
            field=models.CharField(max_length=200, null=True, verbose_name='question'),
        ),
        migrations.AddField(
            model_name='survey',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='survey',
            name='slug_it',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='survey',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
    ]
