# Generated by Django 2.0.8 on 2018-10-07 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('feedbacks', '0004_auto_20181007_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='id',
        ),
        migrations.AddField(
            model_name='survey',
            name='publishablemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.PublishableModel'),
            preserve_default=False,
        ),
    ]
