# Generated by Django 2.0.8 on 2018-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_auto_20181007_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='feedbacks.Survey'),
        ),
    ]
