# Generated by Django 2.0.8 on 2018-10-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_auto_20181007_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='questions',
            field=models.ManyToManyField(to='feedbacks.Question'),
        ),
    ]
