# Generated by Django 2.0.8 on 2018-10-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_auto_20181007_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.Survey'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.Question'),
        ),
    ]
