# Generated by Django 2.0.8 on 2018-10-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0009_auto_20181009_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer', 'verbose_name_plural': 'answers'},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('author_name', 'question', 'survey')},
        ),
    ]
