# Generated by Django 2.0.8 on 2018-10-13 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0010_auto_20181009_2305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('author_name', 'author', 'question', 'survey')},
        ),
    ]
