# Generated by Django 2.0.8 on 2018-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0012_auto_20181013_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='image')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='label')),
                ('label_it', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
                ('label_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='label')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Survey Cover',
                'verbose_name_plural': 'Survey Covers',
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.URLField(default='', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
