# Generated by Django 2.0.8 on 2018-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0014_auto_20181014_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
    ]
