# Generated by Django 2.0.8 on 2018-10-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0018_auto_20181016_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='question_groups',
            field=models.ManyToManyField(to='feedbacks.QuestionGroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='feedbacks.QuestionGroup'),
        ),
    ]
