# Generated by Django 2.0.8 on 2018-10-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0020_auto_20181016_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='question_groups',
            field=models.ManyToManyField(related_name='surveys', to='feedbacks.QuestionGroup'),
        ),
    ]
