# Generated by Django 2.0.8 on 2018-10-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0021_auto_20181018_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='_type',
            field=models.CharField(default='open', max_length=30, verbose_name='type'),
        ),
    ]
