# Generated by Django 2.0.8 on 2018-10-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0023_auto_20181026_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='feedbacks.Question'),
        ),
    ]
