# Generated by Django 2.0.8 on 2018-10-28 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0025_auto_20181026_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='title')),
                ('upper_index', models.PositiveIntegerField(verbose_name='upper index')),
                ('upper_outcome', models.TextField(verbose_name='upper outcome')),
                ('medium_index', models.PositiveIntegerField(verbose_name='medium index')),
                ('medium_outcome', models.TextField(verbose_name='medium outcome')),
                ('lower_index', models.PositiveIntegerField(verbose_name='lower indez')),
                ('lower_outcome', models.TextField(verbose_name='lower outcome')),
            ],
            options={
                'verbose_name': 'outcome',
                'verbose_name_plural': 'outcomes',
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content_en',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content_it',
            field=models.TextField(null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='feedbacks.Question', verbose_name='question'),
        ),
    ]
