# Generated by Django 2.0.8 on 2018-10-28 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0026_auto_20181028_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='lower_outcome_en',
            field=models.TextField(null=True, verbose_name='lower outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='lower_outcome_it',
            field=models.TextField(null=True, verbose_name='lower outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='medium_outcome_en',
            field=models.TextField(null=True, verbose_name='medium outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='medium_outcome_it',
            field=models.TextField(null=True, verbose_name='medium outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='title_en',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='title_it',
            field=models.CharField(max_length=60, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='upper_outcome_en',
            field=models.TextField(null=True, verbose_name='upper outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='upper_outcome_it',
            field=models.TextField(null=True, verbose_name='upper outcome'),
        ),
        migrations.AddField(
            model_name='survey',
            name='outcome',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey', to='feedbacks.Outcome'),
        ),
    ]
