# Generated by Django 2.0.8 on 2018-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0027_auto_20181028_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='lower_index',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='medium_index',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='upper_index',
        ),
        migrations.AddField(
            model_name='outcome',
            name='lower_score',
            field=models.PositiveIntegerField(default=0, verbose_name='lower score'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='medium_score',
            field=models.PositiveIntegerField(default=0, verbose_name='medium score'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='upper_score',
            field=models.PositiveIntegerField(default=0, verbose_name='upper score'),
        ),
    ]
