# Generated by Django 2.0.8 on 2018-10-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0028_auto_20181028_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='title_it',
            field=models.CharField(max_length=200, null=True, verbose_name='title'),
        ),
    ]
