# Generated by Django 2.0.8 on 2018-10-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0029_auto_20181028_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionchoice',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='description_it',
        ),
    ]
