# Generated by Django 2.0.8 on 2018-10-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0030_auto_20181028_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='score'),
        ),
    ]
