# Generated by Django 2.0.13 on 2019-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0032_auto_20190202_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='image',
            field=models.URLField(default='', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
    ]
