# Generated by Django 2.0.13 on 2019-03-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0033_auto_20190322_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyCover',
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='order_index',
            field=models.PositiveIntegerField(default=1, verbose_name='order index'),
            preserve_default=False,
        ),
    ]
