# Generated by Django 2.0.8 on 2019-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0034_auto_20190322_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
