# Generated by Django 2.0.13 on 2019-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0035_survey_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
            preserve_default=False,
        ),
    ]
