# Generated by Django 2.1.7 on 2019-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0037_remove_survey_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='public',
            field=models.BooleanField(default=False, verbose_name='public'),
            preserve_default=False,
        ),
    ]
