# Generated by Django 2.1.7 on 2019-04-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0038_survey_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='image',
            field=models.URLField(blank=True, verbose_name='image'),
        ),
    ]
