# Generated by Django 2.2.13 on 2020-08-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0041_auto_20200727_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='featured',
        ),
    ]
