# Generated by Django 2.2.13 on 2020-08-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0042_remove_survey_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='outcome',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
