# Generated by Django 2.2.28 on 2022-09-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0043_auto_20200825_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='hot',
            field=models.BooleanField(default=False, verbose_name='hot'),
        ),
    ]
