# Generated by Django 2.2.28 on 2022-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0044_survey_hot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='hot',
        ),
        migrations.AddField(
            model_name='survey',
            name='pinned',
            field=models.BooleanField(default=True, help_text='Pinned surveys appear on the landing page', verbose_name='pinned'),
        ),
    ]
