# Generated by Django 2.2.28 on 2026-08-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0045_auto_20220917_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='pinned',
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='subtitle'),
        ),
    ]
