# Generated by Django 2.2.28 on 2026-08-29 14:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0046_auto_20260829_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='prefix',
            field=models.TextField(blank=True, verbose_name='prefix text'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description_it',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='subtitle',
            field=models.CharField(blank=True, max_length=60, verbose_name='subtitle'),
        ),
    ]
