# Generated by Django 2.2.28 on 2026-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0047_auto_20260829_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='prefix_en',
            field=models.TextField(blank=True, null=True, verbose_name='prefix text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='prefix_it',
            field=models.TextField(blank=True, null=True, verbose_name='prefix text'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='subtitle'),
        ),
        migrations.AddField(
            model_name='survey',
            name='subtitle_it',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='subtitle'),
        ),
    ]
